### ISSUE TITLE
Exception on dragging outside [Grid layout]

### ISSUE THREAD

**Issue by vinayak-garg** [h6ah4i/android-advancedrecyclerview#115]
Hi, 
I tried the drag and drop on Grid layout. It works nicely, except for this one issue - 

Lets say the activity contains the recycler view (grid) in 50% bottom region. And their are sufficient items, so that there are several (say 12) rows in the grid. Now grab an item from last row, and drag it up, fast. The finger should move into the top 50% region, which is outside the recycler view. Now the grabbed items floats above other items, but no swapping is happening. And if the item is released in this situation, the app crashes with this library's exception - 

    java.lang.IllegalStateException: onDragItemFinished() - may be a bug (mDraggingItem != holder)
            at com.h6ah4i.android.widget.advrecyclerview.draggable.DraggableItemWrapperAdapter.onDragItemFinished(DraggableItemWrapperAdapter.java:257)
            at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.finishDragging(RecyclerViewDragDropManager.java:765)
            at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.handleActionUpOrCancel(RecyclerViewDragDropManager.java:804)
            at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.onTouchEvent(RecyclerViewDragDropManager.java:526)
            at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager$1.onTouchEvent(RecyclerViewDragDropManager.java:198)

Moving out is perhaps leading to failed condition `draggingItem.getItemId() == draggingItemId` 

And it would be great to have this feature - While dragging an item from second last row to last row, we should be able to drag to empty columns in last row. This should move the very last item.

Thanks!

**Comment by h6ah4i** [comment]
Fixed in 0.8.0.
