### ISSUE TITLE
NullPointerException after migration to v. 0.8.0

### ISSUE THREAD

**Issue by vorsichtdiekurve** [h6ah4i/android-advancedrecyclerview#121]
Hi,
I'm trying to migrate to the new version of the library in order to use some of the newly implemented features. In my adapter, I'm implementing both the dragable, and the swipableItemAdapter interfaces.
I get a NullPointerException at the end of the swipe animation, and often at the end of the drag & drop animation.
Here's the stacktrace:

java.lang.NullPointerException: Attempt to invoke interface method 'void android.support.v4.view.ViewPropertyAnimatorUpdateListener.onAnimationUpdate(android.view.View)' on a null object reference
            at android.support.v4.view.ViewPropertyAnimatorCompatKK$1.onAnimationUpdate(ViewPropertyAnimatorCompatKK.java:28)
            at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationUpdate(ViewPropertyAnimator.java:1193)
            at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1283)
            at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1207)
            at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1248)
            at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:546)
            at android.animation.ValueAnimator.start(ValueAnimator.java:959)
            at android.animation.ValueAnimator.start(ValueAnimator.java:969)
            at android.view.ViewPropertyAnimator.startAnimation(ViewPropertyAnimator.java:905)
            at android.view.ViewPropertyAnimator.start(ViewPropertyAnimator.java:417)
            at android.support.v4.view.ViewPropertyAnimatorCompatICS.start(ViewPropertyAnimatorCompatICS.java:130)
            at android.support.v4.view.ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl.start(ViewPropertyAnimatorCompat.java:497)
            at android.support.v4.view.ViewPropertyAnimatorCompat.start(ViewPropertyAnimatorCompat.java:1235)
            at com.h6ah4i.android.widget.advrecyclerview.animator.impl.BaseItemAnimationManager.startActiveItemAnimation(BaseItemAnimationManager.java:173)
            at com.h6ah4i.android.widget.advrecyclerview.animator.SwipeDismissItemAnimator$SwipeDismissItemRemoveAnimationManager.onCreateAnimation(SwipeDismissItemAnimator.java:138)
            at com.h6ah4i.android.widget.advrecyclerview.animator.SwipeDismissItemAnimator$SwipeDismissItemRemoveAnimationManager.onCreateAnimation(SwipeDismissItemAnimator.java:115)
            at com.h6ah4i.android.widget.advrecyclerview.animator.impl.BaseItemAnimationManager.createAnimation(BaseItemAnimationManager.java:152)
            at com.h6ah4i.android.widget.advrecyclerview.animator.impl.BaseItemAnimationManager.runPendingAnimations(BaseItemAnimationManager.java:91)
            at com.h6ah4i.android.widget.advrecyclerview.animator.GeneralItemAnimator.schedulePendingAnimationsByDefaultRule(GeneralItemAnimator.java:263)
            at com.h6ah4i.android.widget.advrecyclerview.animator.SwipeDismissItemAnimator.onSchedulePendingAnimations(SwipeDismissItemAnimator.java:54)
            at com.h6ah4i.android.widget.advrecyclerview.animator.GeneralItemAnimator.runPendingAnimations(GeneralItemAnimator.java:62)
            at android.support.v7.widget.RecyclerView$2.run(RecyclerView.java:391)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:549)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5306)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

I have tried to migrate both ways, using the LegacySwipeableItemAdapter and implementing the new "SwipeableItemAdapter.onItemSwipe()" method. The result is the same. Does anyone know what the problem might be? Thanks in advance for any help. :)

**Comment by h6ah4i** [comment]
Hi. Thanks for your issue report. I am trying to fix the issue, but I can not reproduce it yet... so I want ask you some questions to investigate the issue. (1) Is the example app also crashes on your device? (2) What version of Android OS running on your device?

**Comment by vorsichtdiekurve** [comment]
Hi,
Thanks for your attention.
1. The example app works fine
2. I've tested the app on 3 different devices, everytime resulting in a crash:
    - Lenovo Yoga Tablet2 with Android 5.0.1
    - HTC Nexus 9 with Android 5.1.1
    - Samsung Galaxy Tab 3 GT-P5200 with Android 4.4.2

The stacktrace for versions 5+ is as the above one. For Android 4.4.2 it's different:
java.lang.NullPointerException
            at com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager.finishSwiping(RecyclerViewSwipeManager.java:561)
            at com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager.cancelSwipe(RecyclerViewSwipeManager.java:649)
            at com.h6ah4i.android.widget.advrecyclerview.swipeable.SwipeableItemWrapperAdapter.cancelSwipe(SwipeableItemWrapperAdapter.java:182)
            at com.h6ah4i.android.widget.advrecyclerview.swipeable.SwipeableItemWrapperAdapter.onHandleWrappedAdapterChanged(SwipeableItemWrapperAdapter.java:138)
            at com.h6ah4i.android.widget.advrecyclerview.utils.BaseWrapperAdapter.onWrappedAdapterChanged(BaseWrapperAdapter.java:144)
            at com.h6ah4i.android.widget.advrecyclerview.utils.BaseWrapperAdapter$BridgeObserver.onChanged(BaseWrapperAdapter.java:190)
            at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:9278)
            at android.support.v7.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:5553)
            at com.h6ah4i.android.widget.advrecyclerview.draggable.DraggableItemWrapperAdapter.onDragItemStarted(DraggableItemWrapperAdapter.java:250)
            at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.startDragging(RecyclerViewDragDropManager.java:599)
            at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.checkConditionAndStartDragging(RecyclerViewDragDropManager.java:835)
            at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.handleOnLongPress(RecyclerViewDragDropManager.java:563)
            at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.access$500(RecyclerViewDragDropManager.java:46)
            at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager$InternalHandler.handleMessage(RecyclerViewDragDropManager.java:1576)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5653)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at dalvik.system.NativeStart.main(Native Method)

Maybe there's something wrong with our gradle scripts? Is there some minimum configuration required for advanced RecyclerView to work properly? Thanks in advance for help.

**Comment by h6ah4i** [comment]
Thanks. Finally I can get reproduced it. What I did to reproduce the issue is changing the return value of the [`getSwipeableContainerView()`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/example/src/main/java/com/h6ah4i/android/example/advrecyclerview/demo_s/MySwipeableItemAdapter.java#L72) method.

from:
```java
public static class MyViewHolder extends AbstractSwipeableItemViewHolder {
    public FrameLayout mContainer;
    ...
    @Override
    public View getSwipeableContainerView() {
        return mContainer;
    }
}
```

to:
```java
public static class MyViewHolder extends AbstractSwipeableItemViewHolder {
    public FrameLayout mContainer;
    ...
    @Override
    public View getSwipeableContainerView() {
        return itemView;
    }
}
```

### How to fix
Create an inner view group for `getSwipeableContainerView()`.

```xml
<!-- layout file for item views -->
<FrameLayout >    --- itemView
    <FrameLayout> --- for getSwipeableContainerView()
    </FrameLayout>
</FrameLayout>
```

---

NOTE: This issue is related to a bug of the support library. NPE can be occurred when using the `ViewPropertyAnimatorCompat.setUpdateListener(view, null)` call. 

I think 

```java
class ViewPropertyAnimatorCompatKK {
    public static void setUpdateListener(final View view,
            final ViewPropertyAnimatorUpdateListener listener) {
        view.animate().setUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
            @Override
            public void onAnimationUpdate(ValueAnimator valueAnimator) {
                listener.onAnimationUpdate(view);
            }
        });
    }
}
```

should be

```java
class ViewPropertyAnimatorCompatKK {
    public static void setUpdateListener(final View view,
            final ViewPropertyAnimatorUpdateListener listener) {
            if (listener != null) {
            view.animate().setUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
                @Override
                public void onAnimationUpdate(ValueAnimator valueAnimator) {
                    listener.onAnimationUpdate(view);
                }
            });
        } else {
            view.animate().setUpdateListener(null);
        }
    }
}
```

I will report this issue to Google, thanks!

**Comment by h6ah4i** [comment]
I created an issue report on the AOSP issue tracker.

- [Issue 189686: NPE can be occurred when using the ViewPropertyAnimatorCompat](https://code.google.com/p/android/issues/detail?id=189686&thanks=189686&ts=1444696802)

**Comment by vorsichtdiekurve** [comment]
Thank you for your help. Works fine now :)

**Comment by kate26** [comment]
04-13 12:44:37.782 6845-6845/com.bwangroup.christprofil E/dalvikvm: Could not find class 'com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager$1', referenced from method com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager.<init>
04-13 12:44:37.782 6845-6845/com.bwangroup.christprofil W/dalvikvm: VFY: unable to resolve new-instance 9264 (Lcom/h6ah4i/android/widget/advrecyclerview/swipeable/RecyclerViewSwipeManager$1;) in Lcom/h6ah4i/android/widget/advrecyclerview/swipeable/RecyclerViewSwipeManager;
04-13 12:44:37.782 6845-6845/com.bwangroup.christprofil D/dalvikvm: VFY: replacing opcode 0x22 at 0x001b
04-13 12:44:37.782 6845-6845/com.bwangroup.christprofil I/dalvikvm: Could not find method com.h6ah4i.android.widget.advrecyclerview.utils.CustomRecyclerViewUtils.getSynchronizedPosition, referenced from method com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager.checkConditionAndStartSwiping
04-13 12:44:37.782 6845-6845/com.bwangroup.christprofil W/dalvikvm: VFY: unable to resolve static method 63875: Lcom/h6ah4i/android/widget/advrecyclerview/utils/CustomRecyclerViewUtils;.getSynchronizedPosition (Landroid/support/v7/widget/RecyclerView$ViewHolder;)I
04-13 12:44:37.782 6845-6845/com.bwangroup.christprofil D/dalvikvm: VFY: replacing opcode 0x71 at 0x0000
04-13 12:44:37.792 6845-6845/com.bwangroup.christprofil I/dalvikvm: Could not find method com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager$InternalHandler.removeDeferredCancelSwipeRequest, referenced from method com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager.finishSwiping
04-13 12:44:37.792 6845-6845/com.bwangroup.christprofil W/dalvikvm: VFY: unable to resolve virtual method 63764: Lcom/h6ah4i/android/widget/advrecyclerview/swipeable/RecyclerViewSwipeManager$InternalHandler;.removeDeferredCancelSwipeRequest ()V
04-13 12:44:37.792 6845-6845/com.bwangroup.christprofil D/dalvikvm: VFY: replacing opcode 0x6e at 0x000b
04-13 12:44:37.792 6845-6845/com.bwangroup.christprofil E/dalvikvm: Could not find class 'com.h6ah4i.android.widget.advrecyclerview.swipeable.SwipeableItemWrapperAdapter', referenced from method com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager.getSwipeableItemWrapperAdapter
04-13 12:44:37.792 6845-6845/com.bwangroup.christprofil W/dalvikvm: VFY: unable to resolve const-class 9273 (Lcom/h6ah4i/android/widget/advrecyclerview/swipeable/SwipeableItemWrapperAdapter;) in Lcom/h6ah4i/android/widget/advrecyclerview/swipeable/RecyclerViewSwipeManager;
04-13 12:44:37.792 6845-6845/com.bwangroup.christprofil D/dalvikvm: VFY: replacing opcode 0x1c at 0x0004
04-13 12:44:37.792 6845-6845/com.bwangroup.christprofil I/dalvikvm: Could not find method com.h6ah4i.android.widget.advrecyclerview.utils.CustomRecyclerViewUtils.findChildViewHolderUnderWithTranslation, referenced from method com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager.handleActionDown
04-13 12:44:37.792 6845-6845/com.bwangroup.christprofil W/dalvikvm: VFY: unable to resolve static method 63867: Lcom/h6ah4i/android/widget/advrecyclerview/utils/CustomRecyclerViewUtils;.findChildViewHolderUnderWithTranslation (Landroid/support/v7/widget/RecyclerView;FF)Landroid/support/v7/widget/RecyclerView$ViewHolder;
04-13 12:44:37.792 6845-6845/com.bwangroup.christprofil D/dalvikvm: VFY: replacing opcode 0x71 at 0x000e
04-13 12:44:37.792 6845-6845/com.bwangroup.christprofil I/dalvikvm: Could not find method com.h6ah4i.android.widget.advrecyclerview.utils.CustomRecyclerViewUtils.findChildViewHolderUnderWithTranslation, referenced from method com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager.handleActionMoveWhileNotSwiping
04-13 12:44:37.792 6845-6845/com.bwangroup.christprofil W/dalvikvm: VFY: unable to resolve static method 63867: Lcom/h6ah4i/android/widget/advrecyclerview/utils/CustomRecyclerViewUtils;.findChildViewHolderUnderWithTranslation (Landroid/support/v7/widget/RecyclerView;FF)Landroid/support/v7/widget/RecyclerView$ViewHolder;
04-13 12:44:37.792 6845-6845/com.bwangroup.christprofil D/dalvikvm: VFY: replacing opcode 0x71 at 0x0085
04-13 12:44:37.792 6845-6845/com.bwangroup.christprofil W/dalvikvm: VFY: Ljava/lang/Object; is not instance of Landroid/support/v7/widget/RecyclerView$Adapter;
04-13 12:44:37.792 6845-6845/com.bwangroup.christprofil W/dalvikvm: VFY: bad arg 0 (into Landroid/support/v7/widget/RecyclerView$Adapter;)
04-13 12:44:37.792 6845-6845/com.bwangroup.christprofil W/dalvikvm: VFY:  rejecting call to Lcom/h6ah4i/android/widget/advrecyclerview/swipeable/RecyclerViewSwipeManager;.getItemPosition (Landroid/support/v7/widget/RecyclerView$Adapter;JI)I
04-13 12:44:37.792 6845-6845/com.bwangroup.christprofil W/dalvikvm: VFY:  rejecting opcode 0x71 at 0x0029
04-13 12:44:37.792 6845-6845/com.bwangroup.christprofil W/dalvikvm: VFY:  rejected Lcom/h6ah4i/android/widget/advrecyclerview/swipeable/RecyclerViewSwipeManager;.handleActionMoveWhileSwiping (Landroid/view/MotionEvent;)V
04-13 12:44:37.792 6845-6845/com.bwangroup.christprofil W/dalvikvm: Verifier rejected class Lcom/h6ah4i/android/widget/advrecyclerview/swipeable/RecyclerViewSwipeManager;
04-13 12:44:37.792 6845-6845/com.bwangroup.christprofil D/AndroidRuntime: Shutting down VM
04-13 12:44:37.802 6845-6845/com.bwangroup.christprofil W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x418398b0)
04-13 12:44:37.812 6845-6845/com.bwangroup.christprofil E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          java.lang.VerifyError: com/h6ah4i/android/widget/advrecyclerview/swipeable/RecyclerViewSwipeManager
                                                                              at com.bwangroup.christprofil.activities.DetailCategorieActivity.onCreate(DetailCategorieActivity.java:92)
                                                                              at android.app.Activity.performCreate(Activity.java:5133)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2225)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2311)
                                                                              at android.app.ActivityThread.access$600(ActivityThread.java:149)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                              at android.os.Looper.loop(Looper.java:137)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5214)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:525)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
                                                                              at dalvik.system.NativeStart.main(Native Method)

**Comment by kate26** [comment]
please help me

**Comment by vorsichtdiekurve** [comment]
Looks like this issue could be related to multidex. Do you have multidex support enabled in your project?

**Comment by h6ah4i** [comment]
@kate26 Hi. It seems not my library's fault. Try using the latest Android build tools, and check your build.gradle script. The following post might be help.
https://plus.google.com/+EtienneLawlor/posts/FhQrfWU2uY4
