### ISSUE TITLE
Not compatible with RecyclerView 23.1.0

### ISSUE THREAD

**Issue by solcott** [h6ah4i/android-advancedrecyclerview#130]
Looks like Google made some backwards incompatible changes.  When I try to use advanced recyclerview in my app I get AbstractMethodErrors.

I tried updating Advanced RecyclerView to compile using 23.1.0 of recyclerview and app compat and making BaseItemAnimator extend android.support.v7.widget.SimpleItemAnimator.  However I get exceptions when running the example app.

On Swipe, Drag, Expand I get the following exception:
java.lang.IllegalStateException: item is null
at com.h6ah4i.android.widget.advrecyclerview.animator.impl.BaseItemAnimationManager.addActiveAnimationTarget(BaseItemAnimationManager.java:178)
at com.h6ah4i.android.widget.advrecyclerview.animator.impl.BaseItemAnimationManager.startActiveItemAnimation(BaseItemAnimationManager.java:172)
at com.h6ah4i.android.widget.advrecyclerview.animator.SwipeDismissItemAnimator$SwipeDismissItemChangeAnimationManager.onCreateChangeAnimationForNewItem(SwipeDismissItemAnimator.java:250)
at com.h6ah4i.android.widget.advrecyclerview.animator.impl.ItemChangeAnimationManager.onCreateAnimation(ItemChangeAnimationManager.java:64)
at com.h6ah4i.android.widget.advrecyclerview.animator.impl.ItemChangeAnimationManager.onCreateAnimation(ItemChangeAnimationManager.java:24)
at com.h6ah4i.android.widget.advrecyclerview.animator.impl.BaseItemAnimationManager.createAnimation(BaseItemAnimationManager.java:152)
at com.h6ah4i.android.widget.advrecyclerview.animator.impl.BaseItemAnimationManager.runPendingAnimations(BaseItemAnimationManager.java:91)
at com.h6ah4i.android.widget.advrecyclerview.animator.GeneralItemAnimator.schedulePendingAnimationsByDefaultRule(GeneralItemAnimator.java:275)
at com.h6ah4i.android.widget.advrecyclerview.animator.SwipeDismissItemAnimator.onSchedulePendingAnimations(SwipeDismissItemAnimator.java:54)
at com.h6ah4i.android.widget.advrecyclerview.animator.GeneralItemAnimator.runPendingAnimations(GeneralItemAnimator.java:62)
at android.support.v7.widget.RecyclerView$2.run(RecyclerView.java:394)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
at android.view.Choreographer.doCallbacks(Choreographer.java:670)
at android.view.Choreographer.doFrame(Choreographer.java:603)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by h6ah4i** [comment]
Thanks for your report! I'll take a look on this weekend.

**Comment by ArcanusEternal** [comment]
Same here :(

**Comment by marbat87** [comment]
I got an error too (maybe the same, I don't remember), but I solved it replacing
<pre>
final GeneralItemAnimator animator = new RefactoredDefaultItemAnimator();
animator.setSupportsChangeAnimations(false);
mRecyclerView.setItemAnimator(animator);
</pre>

with
<pre>
final RecyclerView.ItemAnimator animator = mRecyclerView.getItemAnimator();
        if (animator instanceof SimpleItemAnimator) {
            ((SimpleItemAnimator) animator).setSupportsChangeAnimations(false);
        }
</pre>

in my class: it seems to work fine.

**Comment by h6ah4i** [comment]
Hi. I've just published v0.8.2 which is compatible with RecyclerView 23.1.0 :wink:
