### ISSUE TITLE
SwipeableItemWrapperAdapter.onViewRecycled crash

### ISSUE THREAD

**Issue by thefex** [h6ah4i/android-advancedrecyclerview#145]
My application logged another crash on activity destroy due to AdvancedRecyclerView (SwipeableItemWrapperAdapter.onViewRecycled)

java.lang.NullPointerException
	at com.h6ah4i.android.widget.advrecyclerview.swipeable.SwipeableItemWrapperAdapter.onViewRecycled(SwipeableItemWrapperAdapter.java:77)
	at android.support.v7.widget.RecyclerView$Recycler.dispatchViewRecycled(RecyclerView.java:4912)
	at android.support.v7.widget.RecyclerView$Recycler.addViewHolderToRecycledViewPool(RecyclerView.java:4678)
	at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:4661)
	at android.support.v7.widget.RecyclerView.removeAnimatingView(RecyclerView.java:1091)
	at android.support.v7.widget.RecyclerView.access$6200(RecyclerView.java:144)
	at android.support.v7.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(RecyclerView.java:9541)
	at android.support.v7.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:10017)
	at android.support.v7.widget.SimpleItemAnimator.dispatchRemoveFinished(SimpleItemAnimator.java:252)
	at com.h6ah4i.android.widget.advrecyclerview.animator.impl.ItemRemoveAnimationManager.dispatchFinished(ItemRemoveAnimationManager.java:54)
	at com.h6ah4i.android.widget.advrecyclerview.animator.impl.ItemRemoveAnimationManager.dispatchFinished(ItemRemoveAnimationManager.java:24)
	at com.h6ah4i.android.widget.advrecyclerview.animator.impl.BaseItemAnimationManager$BaseAnimatorListener.onAnimationEnd(BaseItemAnimationManager.java:227)
	at android.support.v4.view.ViewPropertyAnimatorCompatJB$1.onAnimationEnd(ViewPropertyAnimatorCompatJB.java:47)
	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1030)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1056)
	at android.animation.ValueAnimator.cancel(ValueAnimator.java:969)
	at android.view.ViewPropertyAnimator.cancel(ViewPropertyAnimator.java:412)
	at android.support.v4.view.ViewPropertyAnimatorCompatICS.cancel(ViewPropertyAnimatorCompatICS.java:102)
	at android.support.v4.view.ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl.cancel(ViewPropertyAnimatorCompat.java:462)
	at android.support.v4.view.ViewPropertyAnimatorCompat.cancel(ViewPropertyAnimatorCompat.java:1049)
	at com.h6ah4i.android.widget.advrecyclerview.animator.impl.BaseItemAnimationManager.cancelAllStartedAnimations(BaseItemAnimationManager.java:63)
	at com.h6ah4i.android.widget.advrecyclerview.animator.GeneralItemAnimator.endAnimations(GeneralItemAnimator.java:181)
	at android.support.v7.widget.RecyclerView.onDetachedFromWindow(RecyclerView.java:2067)
	at android.view.View.dispatchDetachedFromWindow(View.java:13549)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2800)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2800)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4068)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4041)
	at android.view.ViewGroup.removeView(ViewGroup.java:3973)
	at android.support.v4.view.ViewPager.removeView(ViewPager.java:1359)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1178)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1241)
	at android.support.v4.app.FragmentManagerImpl.dispatchDestroyView(FragmentManager.java:2084)
	at android.support.v4.app.Fragment.performDestroyView(Fragment.java:2167)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1152)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1241)
	at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2090)
	at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:235)
	at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:326)
	at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:161)
	at md54090ab44571a8c6cc99872905c9f38e0.BaseMvxActivity_1.n_onDestroy(Native Method)
	at md54090ab44571a8c6cc99872905c9f38e0.BaseMvxActivity_1.onDestroy(BaseMvxActivity_1.java:46)
	at android.app.Activity.performDestroy(Activity.java:5631)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1123)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3787)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3818)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4018)
	at android.app.ActivityThread.access$1000(ActivityThread.java:172)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1311)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5598)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)

Investigating issue.

**Comment by h6ah4i** [comment]
Hi. Thank you for reporting the issue.

I will fix this ASAP, but maybe it can be avoided by calling `mRecyclerView.setAdapter(null)` in `onDestroyView()` of the inner ViewPager Fragment. Thanks.

**Comment by thefex** [comment]
That's interesting what you are saying.
Basically I think we should change the way release methods works cause those null exceptions spawns over and over again.

I think we should use NullObject pattern - instead of "nullyfing" everything in onRelease - we should create Null Objects classes which would be empty implementations of proper interfaces (like RecyclerViewSwipeManager) and set private fields to new instances of that objects.

Those implementations would have empty methods like: OnBindViewHolder and so on - that will prevent NullReferenceExceptions and crashes.

**Comment by thefex** [comment]
To reproduce the issue please enable "Don't keep activities option" in developer settings + go out and back from application on Activity where you use AdvancedRecyclerView

**Comment by thefex** [comment]
Moving RecyclerView.setAdapter(null) before release methods works as workaround.

**Comment by h6ah4i** [comment]
In my opinion, making a null object of the `RecyclerViewSwipeManager` class is not a good idea in this case. If I applying the null object pattern, I'd rather create a inner implementation class of the `SwipeableItemWrapperAdapter` (like `SwipeableItemWrapperAdapter.Impl` which handles all delegated processes of `SwipeableItemWrapperAdapter`) and replace it to null object in `onRelease()`.

However, I think using the null object pattern is too much in this case. It seems that the `onViewRecycled()` is the only method possibly called by RecyclerView even after the wrapper adapter is released.

**Comment by h6ah4i** [comment]
Hi. I have just released v0.8.5. This issue has been fixed.
