### ISSUE TITLE
NPE in 0.8.5

### ISSUE THREAD

**Issue by hexise** [h6ah4i/android-advancedrecyclerview#158]
I found a NPE exception when I upgrade my library to 0.8.5. Here is the trace, this error seems not happen when I use version 0.8.0. And this problem happens on both Android 4.x and 5.x.

Caused by java.lang.NullPointerException
       at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.handleActionUpOrCancel(RecyclerViewDragDropManager.java:746)
       at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.cancelDrag(RecyclerViewDragDropManager.java:651)
       at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.cancelDrag(RecyclerViewDragDropManager.java:647)
       at com.example.MainActivity.onPause(MainActivity.java:156)
       at android.app.Activity.performPause(Activity.java:5530)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1251)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2383)
       at android.app.ActivityThread.access$900(ActivityThread.java:161)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5356)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by h6ah4i** [comment]
Hi. Do you calling the `cancelDrag()` method after calling the `release()` method? 

https://github.com/h6ah4i/android-advancedrecyclerview/blob/0.8.5/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/draggable/RecyclerViewDragDropManager.java#L746

It seems that NPE can be occurred by the following conditions;

- after the `release()` method has been called
- before calling the `attachRecyclerView()` method

**Comment by hexise** [comment]
No, I call cancelDrag() from onPause() method, and release() from onDestory() method. onPause() should be invoked earlier than onDestroy().

**Comment by hexise** [comment]
Hello, I think I found the problem according your comment:

I only attach the drag and drop manager to recycler view after my data retrieved(I receive data from my service, so this happens in onServiceConnected() method). Maybe onPause() happens before attachRecyclerView(), so make this problem happen. I will add a check in onPause() method to avoid this kind of problem, I think it should be solved.

Thanks.

**Comment by h6ah4i** [comment]
Hi. I have just added a null check before using mHandler inside of `RecyclerViewDragDropManager` (*). Because the `cancelDrag()` method is invoked inside of the `release()` method and I think this method should be always safe.

(*) commit: 004f6e20bfed6dc2a2cd190542ca2cd3a43fbd25

The above commit will be included to next release, so I keep this issue open until then. Thanks!

**Comment by hexise** [comment]
Thank you!
