### ISSUE TITLE
Crash of app with v0.8.5

### ISSUE THREAD

**Issue by rusmatreshka** [h6ah4i/android-advancedrecyclerview#160]
I've only included this line:
compile ('com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.8.5@aar'){
        transitive = true;
    } 
in my gradle and app start to crash with this stack trace:
12-04 01:11:05.490 30925-30925/com.voodoomobile.friendzone E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.voodoomobile.friendzone, PID: 30925
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.voodoomobile.friendzone/com.voodoomobile.friendzone.MainActivity}: android.view.InflateException: Binary XML file line #16: Error inflating class android.support.design.widget.NavigationView
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                              Caused by: android.view.InflateException: Binary XML file line #16: Error inflating class android.support.design.widget.NavigationView
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
                                                                                 at com.voodoomobile.friendzone.MainActivity.onCreate(MainActivity.java:51)
                                                                                 at android.app.Activity.performCreate(Activity.java:5990)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:135) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                              Caused by: java.lang.reflect.InvocationTargetException
                                                                                 at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                 at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                                 at com.voodoomobile.friendzone.MainActivity.onCreate(MainActivity.java:51) 
                                                                                 at android.app.Activity.performCreate(Activity.java:5990) 
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:135) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                              Caused by: java.lang.NoClassDefFoundError: android.support.design.internal.NavigationMenuPresenter
                                                                                 at android.support.design.widget.NavigationView.<init>(NavigationView.java:82)
                                                                                 at android.support.design.widget.NavigationView.<init>(NavigationView.java:94)
                                                                                 at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                                 at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                                 at com.voodoomobile.friendzone.MainActivity.onCreate(MainActivity.java:51) 
                                                                                 at android.app.Activity.performCreate(Activity.java:5990) 
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:135) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 

v0.8.4 works fine

**Comment by h6ah4i** [comment]
Hi. I think the crash stack trace seems something weird...

The only thing that may cause the problem is the version of `appcompat-v7` and `recyclerview-v7` libraries. I have updated those libraries to v23.1.1 since Advanced RecyclerView v0.8.5.

Try the following code in your `build.gradle`, it specifies to use `appcompat-v7` and `recyclerview-v7` **v23.1.0** with Advanced RecyclerView **v0.8.5**.

```groovy
compile ('com.android.support:appcompat-v7:23.1.0')
compile ('com.android.support:recyclerview-v7:23.1.0')

compile ('com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.8.5') {
    exclude group: 'com.android.support', module: 'recyclerview-v7'
    exclude group: 'com.android.support', module: 'appcompat-v7'
}
```

**Comment by h6ah4i** [comment]
@rusmatreshka Hi. Have you solved this issue?

**Comment by blackDiamonds38** [comment]
is the problem solved.?? What is the solution of this

**Comment by h6ah4i** [comment]
@blackDiamonds38 Maybe, this issue is a Samsung devices specific bug. Please check the following page for the details. Thanks.

http://anasambri.com/android/special-place-for-samsung-in-android-hell.html
