### ISSUE TITLE
Help understanding IllegalStateException

### ISSUE THREAD

**Issue by FreakTheMighty** [h6ah4i/android-advancedrecyclerview#162]
I have implemented a "swipe to reveal button" interface and was playing around with the swipe gesture in my application. I'm having trouble replicating the issue, but one time I crashed the application while swiping. Unfortunately I don't think I will be able to upload a minimal failing example, but was hoping you might be able to point me in the right direction for fixing the problem.

Versions
```
Android:6.0
advrecyclerview:0.7.2
support-v4:22.2.0'
 ```
I get this traceback:
```java
java.lang.IllegalStateException: after animation is cancelled, item should not be in the active animation list [slide]
        at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator.endAnimation(ItemSlidingAnimator.java:278)
        at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator.animateSlideInternal(ItemSlidingAnimator.java:219)
        at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator.animateSlideInternalCompat(ItemSlidingAnimator.java:148)
        at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator.slideToSpecifiedPositionInternal(ItemSlidingAnimator.java:91)
        at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator.slideToSpecifiedPosition(ItemSlidingAnimator.java:67)
        at com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager.slideItem(RecyclerViewSwipeManager.java:689)
        at com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager.applySlideItem(RecyclerViewSwipeManager.java:763)
        at com.h6ah4i.android.widget.advrecyclerview.swipeable.SwipingItemOperator.update(SwipingItemOperator.java:107)
        at com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager.handleActionMoveWhileSwiping(RecyclerViewSwipeManager.java:567)
        at com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager.onTouchEvent(RecyclerViewSwipeManager.java:432)
        at com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager$1.onTouchEvent(RecyclerViewSwipeManager.java:262)
        at android.support.v7.widget.RecyclerView.dispatchOnItemTouch(RecyclerView.java:1991)
        at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2116)
        at android.view.View.dispatchTouchEvent(View.java:9294)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2765)
        at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
        at android.view.View.dispatchPointerEvent(View.java:9514)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3
```

**Comment by h6ah4i** [comment]
Hi. Thanks for reporting the issue.

I am not sure what is the cause of this problem, but I guess it is related to the item view recycling mechanism. This library has a bug until v0.8.3 which is triggered when item view is recycled during swipe animation is still running.

ref.) Item swipe completes after holder recycled #136 

BTW, why are you still using old version of this library? Is there any reason?

**Comment by FreakTheMighty** [comment]
Hi @h6ah4i , I've been holding off upgrading until I have a little more bandwidth to handle any migration issues. The problem hasn't presented itself frequently, so I can afford to put the upgrade off for a little bit.

Thank you for your response. I'm going to close this. I"ll reopen it if I find it in later versions.
