### ISSUE TITLE
crash bugs 

### ISSUE THREAD

**Issue by mkrcpp** [h6ah4i/android-advancedrecyclerview#173]
com.jdhome.modules.home.HomeFragment.onPause(HomeFragment.java:131)
```
 @Override
    public void onPause() {
        mRecyclerViewDragDropManager.cancelDrag();
        super.onPause();
    }
```

which is in "mRecyclerViewDragDropManager.cancelDrag();"  got the error.

```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                            Process: com.jdhome, PID: 15345
                                                            java.lang.RuntimeException: Unable to pause activity {com.jdhome/com.jdhome.modules.MainActivity}: java.lang.NullPointerException
                                                                at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3319)
                                                                at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3264)
                                                                at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3242)
                                                                at android.app.ActivityThread.access$1300(ActivityThread.java:139)
                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1267)
                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                at android.os.Looper.loop(Looper.java:136)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5315)
                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                                at dalvik.system.NativeStart.main(Native Method)
                                                             Caused by: java.lang.NullPointerException
                                                                at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.handleActionUpOrCancel(RecyclerViewDragDropManager.java:746)
                                                                at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.cancelDrag(RecyclerViewDragDropManager.java:651)
                                                                at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.cancelDrag(RecyclerViewDragDropManager.java:647)
                                                                at com.jdhome.modules.home.HomeFragment.onPause(HomeFragment.java:131)
                                                                at android.support.v4.app.Fragment.performPause(Fragment.java:2123)
                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1118)
                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
                                                                at android.support.v4.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:2056)
                                                                at android.support.v4.app.FragmentController.dispatchPause(FragmentController.java:198)
                                                                at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:401)
                                                                at android.app.Activity.performPause(Activity.java:5452)
                                                                at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1244)
                                                                at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3295)
                                                                at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3264) 
                                                                at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3242) 
                                                                at android.app.ActivityThread.access$1300(ActivityThread.java:139) 
                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1267) 
                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                at android.os.Looper.loop(Looper.java:136) 
                                                                at android.app.ActivityThread.main(ActivityThread.java:5315) 
                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864) 
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680) 
                                                                at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by h6ah4i** [comment]
Thanks for the report. I will take it a look.

**Comment by mkrcpp** [comment]
It is my pleasure, this bug happened just one time,when I want to move item.
 I kill the app process and reopen the app, and everything normally, but when I move item,got the error.
I am surly mRecyclerViewDragDropManager is not null .

thank you for your android-advancedrecyclerview, I really like it .

**Comment by mkrcpp** [comment]
I find another bug
https://github.com/h6ah4i/android-advancedrecyclerview/issues/176

**Comment by h6ah4i** [comment]
Hi. This issue seems the same as issue #158. 

- NPE in 0.8.5 (#158)

> It seems that NPE can be occurred by the following conditions;
> - after the release() method has been called
> - before calling the attachRecyclerView() method
