### ISSUE TITLE
NullPointerException when expanding some/most items using support library v23.2.0

### ISSUE THREAD

**Issue by jhavatar** [h6ah4i/android-advancedrecyclerview#202]
Hi

After I updated from support lib v23.1.1 & advrecyclerview v0.8.1 to support library v23.2.0 using either advrecyclerview v0.8.1 or v0.8.6 --- when I expand some items in my Advanced RecyclerView I get a NullPointerException:

```
03-02 16:51:47.958 19056-19056/? E/AndroidRuntime: FATAL EXCEPTION: main Process: com.spreeza.shop.dev.debug, PID: 19056 java.lang.NullPointerException: Attempt to read from field 'int android.support.v7.widget.RecyclerView$ItemAnimator$ItemHolderInfo.left' on a null object reference
at android.support.v7.widget.SimpleItemAnimator.animateDisappearance(SimpleItemAnimator.java:78)
at android.support.v7.widget.RecyclerView.animateDisappearance(RecyclerView.java:3246)
at android.support.v7.widget.RecyclerView.access$700(RecyclerView.java:147)
at android.support.v7.widget.RecyclerView$4.processDisappeared(RecyclerView.java:422)
at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:231)
at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3086)
at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2914)
at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3277)
at android.view.View.layout(View.java:15686)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
at android.view.View.layout(View.java:15686)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at android.view.View.layout(View.java:15686)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at android.view.View.layout(View.java:15686)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:122)
at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1139)
at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:810)
at android.view.View.layout(View.java:15686)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
at android.view.View.layout(View.java:15686)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at android.view.View.layout(View.java:15686)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1183)
at android.view.View.layout(View.java:15686)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
at android.view.View.layout(View.java:15686)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1087)
at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:797)
at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:811)
at android.view.View.layout(View.java:15686)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at android.view.View.layout(View.java:15686)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
at android.view.View.layout(View.java:15686)
at android.view.ViewGroup.layout(V
```

Any ideas?

**Comment by h6ah4i** [comment]
@jhavatar Hi. Thank you for your issue report.

Could you try the latest develop branch code through JitPack? I have already updated the support library to v23.2.0 in this branch, but it is not fully tested yet.

```gradle
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile 'com.github.h6ah4i:android-advancedrecyclerview:880f9f07204337dc3c9c1287bc2b46bdf19bca76'
}
```

**Comment by jhavatar** [comment]
Hi @h6ah4i 
Tried it and still get the same results/exception.

**Comment by h6ah4i** [comment]
@jhavatar Thanks, I am going to investigate this issue on this weekend.

**Comment by h6ah4i** [comment]
@jhavatar 
Unfortunately, it seems a bug of the RecyclerView v23.2.0 and it has already been reported to Google.

- [Issue 193958: NullPointerException: Attempt to read from field 'int android.support.v7.widget.RecyclerView$ItemAnimator$ItemHolderInfo.left' on a null object reference	](https://code.google.com/p/android/issues/detail?id=193958&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars#makechanges)

**Comment by h6ah4i** [comment]
memo.
- [StackOverflow - NullPointerException in dissapearence animation of RecyclerView from support v.23.2.0](http://stackoverflow.com/questions/35619022/nullpointerexception-in-dissapearence-animation-of-recyclerview-from-support-v-2)

**Comment by jhavatar** [comment]
thanks @h6ah4i, I will skip v23.2.0 then.

**Comment by xgear-public** [comment]
@h6ah4i looks like google fixed issue you mentioned in 23.2.1 support lib release

**Comment by jhavatar** [comment]
Thanks for heads-up @h6ah4i,  23.2.1 support lib with advrecyclerview:0.8.6 works with zero problems. You can close this issue.

**Comment by h6ah4i** [comment]
@jhavatar @xgear-public : Thank you for your information :wink:
