### ISSUE TITLE
SwitchCompat in Group View NullPointerException

### ISSUE THREAD

**Issue by ibrahim132** [h6ah4i/android-advancedrecyclerview#239]
I added SwitchCompat to the Group layout and i want to save it's state.
```java
@Override
    public void onBindGroupViewHolder(MyGroupViewHolder holder, int groupPosition, int viewType) {
        // child item
        final AbstractAddRemoveExpandableDataProvider.GroupData item = mProvider.getGroupItem(groupPosition);

        // set text
        holder.tvName.setText(item.getName());

        if (holder.switchCompat != null) {

            if (item.isChecked()) {

                holder.tvName.setText(item.getName() + " On"); // Working normally

                if (!holder.switchCompat.isChecked())
                    holder.switchCompat.setChecked(true); // NullPointerException

            } else {

                holder.tvName.setText(item.getName() + " Off"); // Working normally

                if (holder.switchCompat.isChecked())
                    holder.switchCompat.setChecked(false); // NullPointerException

            }

        } else {

            Log.d("SWITCHNULL", "container is null");

        }

        // mark as clickable
        holder.itemView.setClickable(true);

        // set background resource (target view ID: container)
        final int expandState = holder.getExpandStateFlags();

        if ((expandState & Expandable.STATE_FLAG_IS_UPDATED) != 0) {
            int bgResId;

            if ((expandState & Expandable.STATE_FLAG_IS_EXPANDED) != 0) {
                bgResId = R.drawable.bg_group_item_expanded_state;
            } else {
                bgResId = R.drawable.bg_group_item_normal_state;
            }

            holder.mContainer.setBackgroundResource(bgResId);
        }

    }
```
My logcat:
```java
java.lang.NullPointerException
    at com.mypackagename.advancedrecyvlerview.AddRemoveExpandableExampleAdapter.onClickItemSwitchView(AddRemoveExpandableExampleAdapter.java:299)
    at com.mypackagename.advancedrecyvlerview.AddRemoveExpandableExampleAdapter$2.onCheckedChanged(AddRemoveExpandableExampleAdapter.java:43)
    at android.widget.CompoundButton.setChecked(CompoundButton.java:137)
    at android.support.v7.widget.SwitchCompat.setChecked(SwitchCompat.java:802)
    at com.mypackagename.advancedrecyvlerview.AddRemoveExpandableExampleAdapter.onBindGroupViewHolder(AddRemoveExpandableExampleAdapter.java:188)
    at com.mypackagename.advancedrecyvlerview.AddRemoveExpandableExampleAdapter.onBindGroupViewHolder(AddRemoveExpandableExampleAdapter.java:23)
    at com.h6ah4i.android.widget.advrecyclerview.expandable.ExpandableRecyclerViewWrapperAdapter.onBindViewHolder(ExpandableRecyclerViewWrapperAdapter.java:197)
    at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5504)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4741)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
    at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1180)
    at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1031)
    at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4061)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:814)
    at android.view.Choreographer.doCallbacks(Choreographer.java:614)
    at android.view.Choreographer.doFrame(Choreographer.java:583)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:800)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:146)
    at android.app.ActivityThread.main(ActivityThread.java:5602)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
    at dalvik.system.NativeStart.main(Native Method)
```
Check layout  group_item:
<?xml version="1.0" encoding="utf-8"?>
```java
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="60dp"
    android:layout_marginTop="8dp"
    android:background="#ffffff">

    <RelativeLayout
        android:id="@+id/container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clickable="true"
        android:foreground="?attr/selectableItemBackground">

        <android.support.v7.widget.SwitchCompat
            android:id="@+id/sc_switch"
            android:textOn="On"
            android:textOff="Off"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:layout_alignParentEnd="true"
            android:padding="10dp" />

        <TextView
            android:id="@+id/tv_name"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_alignParentStart="true"
            android:layout_toStartOf="@id/sc_switch"
            android:gravity="center" />

    </RelativeLayout>

</FrameLayout>
```

**Comment by h6ah4i** [comment]
Hi. This seems not a bug of Advanced RecyclerView. 
The `NullPointerException` occurres inside of the `onClickItemSwitchView()` method you have implemented. I need more code (at least the code listed on the stack trace) to give you more advices. Thanks.

**Comment by ibrahim132** [comment]
My `onClickItemSwitchView()` method:
```java
void onClickItemSwitchView(View v, boolean isChecked) {
        RecyclerView.ViewHolder vh = RecyclerViewAdapterUtils.getViewHolder(v);
        int flatPosition = vh.getAdapterPosition();

        if (flatPosition == RecyclerView.NO_POSITION) {
            return;
        }

        long expandablePosition = mExpandableItemManager.getExpandablePosition(flatPosition);
        int groupPosition = RecyclerViewExpandableItemManager.getPackedPositionGroup(expandablePosition);

        switch (v.getId()) {
            // common events
            case R.id.sc_switch:

                handleOnClickGroupItemSwitchView(groupPosition, isChecked);

                break;
            default:
                throw new IllegalStateException("Unexpected click event");
        }
    }
```

**Comment by h6ah4i** [comment]
@ibrahim132 Hi. I have tried to reproduce the same issue, but I cannot reproduce it yet. It works fine even though all your code is included to my codebase.

- [experiment_issue_239 branch](https://github.com/h6ah4i/android-advancedrecyclerview/tree/experiment_issue_239)

Please take it a look the code which is pointed by the stack trace carefully. For now, I recommend to put a breakpoint on the line 239 of AddRemoveExpandableExampleAdapter class.

Thanks.

**Comment by ibrahim132** [comment]
@h6ah4i Hi. I downloaded your sample code and i can see the error.
Steps to reproduce the bug:
1- Add more than 10 groups.
2- Expand 4 groups.
3- Scrolling up/down.

Thank you for your replay :).

**Comment by h6ah4i** [comment]
@ibrahim132 Hi. Thanks, now I can reproduce the bug.

```java
void onClickItemSwitchView(View v, boolean isChecked) {
    RecyclerView.ViewHolder vh = RecyclerViewAdapterUtils.getViewHolder(v);
    int flatPosition = vh.getAdapterPosition();  // This line causes a NPE, because 'vh' is null!
    ...
}
```

This is not a bug of ARV. The `RecyclerViewAdapterUtils.getViewHolder()` method returns `null` in this situation. In `onBindViewHolder` the itemView is not added as a child of the `RecyclerView` yet, so the passed `SwitchCompat` also does not have a `RecyclerView` ancestor.

---

I suggest some workarounds;

#### 1. Clear on checked change listener during setChecked()

```java
switchCompat.setOnCheckedChangeListener(null);
switchCompat.setChecked(true);
switchCompat.setOnCheckedChangeListener(mOnCheckedChangeListener);
```

#### 2. Use a flag to detect whether the checked state is set from code

```java
boolean mInsideSetChecked;

mInsideSetChecked = true;
switchCompat.setChecked(true);
mInsideSetChecked = false;


void onClickItemSwitchView(View v, boolean isChecked) {
    if(mInsideSetChecked) {
        return;
    }
    ...
}
```

### 3. Just return if `getViewHolder()` returns `null`

```java
void onClickItemSwitchView(View v, boolean isChecked) {
    RecyclerView.ViewHolder vh = RecyclerViewAdapterUtils.getViewHolder(v);
    if (vh == null) {
        return;
    }
    ...
}
```

**Comment by ibrahim132** [comment]
Hi. It's working now. Thank you man for your time. :+1:
