### ISSUE TITLE
NullPointerException cant destroy Activity

### ISSUE THREAD

**Issue by Nammari** [h6ah4i/android-advancedrecyclerview#254]
Some devices reports this issue 

library version **`0.8.6`**
```
java.lang.RuntimeException: Unable to destroy activity {com.company.app/com.company.app.ui.activity.HomeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.support.v7.widget.RecyclerView$Adapter.b(int)' on a null object reference
1	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3928)
2	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3946)
3	at android.app.ActivityThread.access$1500(ActivityThread.java:154)
4	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1443)
5	at android.os.Handler.dispatchMessage(Handler.java:102)
6	at android.os.Looper.loop(Looper.java:224)
7	at android.app.ActivityThread.main(ActivityThread.java:5514)
8	at java.lang.reflect.Method.invoke(Native Method)
9	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11	Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.support.v7.widget.RecyclerView$Adapter.b(int)' on a null object reference
12	at com.company.app.ui.fragment.CategorySubcategoryFragment$1.getSpanSize(CategorySubcategoryFragment.java:66)
13	at android.support.v7.widget.GridLayoutManager$SpanSizeLookup.getSpanGroupIndex(GridLayoutManager.java:953)
14	at android.support.v7.widget.GridLayoutManager.getSpanGroupIndex(GridLayoutManager.java:438)
15	at android.support.v7.widget.GridLayoutManager.getRowCountForAccessibility(GridLayoutManager.java:125)
16	at android.support.v7.widget.RecyclerView$LayoutManager.generateDefaultLayoutParams(RecyclerView.java:8273)
17	onInitializeAccessibilityNodeInfo
18	at android.support.v7.widget.RecyclerView$LayoutManager.generateDefaultLayoutParams(RecyclerView.java:8233)
19	onInitializeAccessibilityNodeInfo
20	at android.support.v7.widget.RecyclerViewAccessibilityDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:59)
21	at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl$1.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:233)
22	at android.support.v4.view.AccessibilityDelegateCompatJellyBean$1.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompatJellyBean.java:61)
23	at android.view.View.onInitializeAccessibilityNodeInfo(View.java:6151)
24	at android.view.View.createAccessibilityNodeInfoInternal(View.java:6112)
25	at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:22359)
26	at android.view.View.createAccessibilityNodeInfo(View.java:6095)
27	at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:145)
28	at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:119)
29	at android.view.View.onInitializeAccessibilityEventInternal(View.java:6049)
30	at android.view.View$AccessibilityDelegate.onInitializeAccessibilityEvent(View.java:22271)
31	at android.support.v4.view.AccessibilityDelegateCompatIcs.onInitializeAccessibilityEvent(AccessibilityDelegateCompatIcs.java:92)
32	at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateIcsImpl.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:179)
33	at android.support.v4.view.AccessibilityDelegateCompat.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:419)
34	at android.support.v7.widget.RecyclerViewAccessibilityDelegate.onInitializeAccessibilityEvent(RecyclerViewAccessibilityDelegate.java:65)
35	at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl$1.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:228)
36	at android.support.v4.view.AccessibilityDelegateCompatJellyBean$1.onInitializeAccessibilityEvent(AccessibilityDelegateCompatJellyBean.java:56)
37	at android.view.View.onInitializeAccessibilityEvent(View.java:6035)
38	at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5902)
39	at android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked(View.java:22210)
40	at android.support.v4.view.AccessibilityDelegateCompatIcs.sendAccessibilityEventUnchecked(AccessibilityDelegateCompatIcs.java:117)
41	at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateIcsImpl.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:210)
42	at android.support.v4.view.AccessibilityDelegateCompat.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:358)
43	at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl$1.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:255)
44	at android.support.v4.view.AccessibilityDelegateCompatJellyBean$1.sendAccessibilityEventUnchecked(AccessibilityDelegateCompatJellyBean.java:82)
45	at android.view.View.sendAccessibilityEventUnchecked(View.java:5885)
46	at android.support.v7.widget.RecyclerView.sendAccessibilityEventUnchecked(RecyclerView.java:2803)
47	at android.view.View$SendViewStateChangedAccessibilityEvent.run(View.java:22396)
48	at android.view.View$SendViewStateChangedAccessibilityEvent.runOrPost(View.java:22429)
49	at android.view.View.notifyViewAccessibilityStateChangedIfNeeded(View.java:8853)
50	at android.view.View.onFocusChanged(View.java:5770)
51	at android.view.View.clearFocusInternal(View.java:5674)
52	at android.view.View.unFocus(View.java:5707)
53	at android.view.ViewGroup.unFocus(ViewGroup.java:994)
54	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4590)
55	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4576)
56	at android.view.ViewGroup.removeView(ViewGroup.java:4507)
57	at android.support.v4.view.ViewPager.removeView(ViewPager.java:1430)
58	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1165)
59	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
60	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
61	at android.support.v4.app.FragmentManagerImpl.dispatchDestroyView(FragmentManager.java:2077)
62	at android.support.v4.app.Fragment.performDestroyView(Fragment.java:2182)
63	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1139)
64	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
65	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
66	at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2083)
67	at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:244)
68	at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:369)
69	at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:193)
70	at android.app.Activity.performDestroy(Activity.java:6441)
71	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1143)
72	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3915)
73	... 9 more
```

**Comment by magicyoung6768** [comment]
Do you release the manager when call `onDestory?`

**Comment by Nammari** [comment]
```
its inside fragment and in onDestroyView method i release the manager , is that correct ? 

>  @Override
>     public void onDestroyView() {
>         super.onDestroyView();
>         if (mRecyclerViewExpandableItemManager != null) {
>             mRecyclerViewExpandableItemManager.release();
>             mRecyclerViewExpandableItemManager = null;
>         }
>         if (mWrappedAdapter != null) {
>             WrapperAdapterUtils.releaseAll(mWrappedAdapter);
>             mWrappedAdapter = null;
>         }
>         ButterKnife.unbind(this);
>     }
```

**Comment by magicyoung6768** [comment]
`ViewPager` it will host  `Fragment ` by  `setOffscreenPageLimit `,be sure create the manager when call `onCreateView`

**Comment by h6ah4i** [comment]
@Nammari Sorry for the late reply. I thought I have already answered to this issue 😞 

First, I took a look at the stack trace and I noticed that there is no lines of code of this library. I am not sure whether the NPE is caused by this library. 

I guess this issue can be avoided by the one of the following approaches;

##### 1. Clear `SpanSizeLookup` in `onDestroyView()`
```java
public void onDestroyView() {
    ...
    ((GridLayoutManager) mRecyclerView.getLayoutManager()).setSpanSizeLookup(null);
    ...
}
```

##### 2. Clear adapter in `onDestroyView()`
```java
public void onDestroyView() {
    ...
    mRecyclerView.setAdapter(null);
    ...
}
```

##### 3. Clear layout manager in `onDestroyView()`
```java
public void onDestroyView() {
    ...
    mRecyclerView.setLayoutManager(null);
    ...
}
```

Thanks.
