### ISSUE TITLE
Tmp detached View recycled before it's removed from RecyclerView causing FATAL EXCEPTION

### ISSUE THREAD

**Issue by LouisCo** [h6ah4i/android-advancedrecyclerview#26]
I am trying to mimic the Lollipop notifications behavior with your library. I only use the Swipe To Dismiss part, without pinning. The swipe of one item works well, but if I swipe out two items without letting the first item the time to be completely dismissed, my app crash with the stack trace below, without any reference of my own project files inside... I don't know what to do... I checked many things in my project and I still can't find the source of this crash... it seems that a ViewHolder in my RecyclerView has been declared available too soon, and the RecyclerView try to use it before it is really available... I would be very grateful to anyone helping me to find the source of this bug.
```
java.lang.IllegalArgumentException: Tmp detached view should be removed from RecyclerView before it can be recycled: ViewHolder{42241e38 position=2 id=222, oldPos=-1, pLpos:-1 tmpDetached no parent}
            at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:4250)
            at android.support.v7.widget.RecyclerView.removeAnimatingView(RecyclerView.java:888)
            at android.support.v7.widget.RecyclerView.access$5100(RecyclerView.java:131)
            at android.support.v7.widget.RecyclerView$ItemAnimatorRestoreListener.onMoveFinished(RecyclerView.java:8736)
            at android.support.v7.widget.RecyclerView$ItemAnimator.dispatchMoveFinished(RecyclerView.java:9061)
            at com.h6ah4i.android.widget.advrecyclerview.animator.impl.ItemMoveAnimationManager.dispatchFinished(ItemMoveAnimationManager.java:54)
            at com.h6ah4i.android.widget.advrecyclerview.animator.impl.ItemMoveAnimationManager.dispatchFinished(ItemMoveAnimationManager.java:24)
            at com.h6ah4i.android.widget.advrecyclerview.animator.impl.BaseItemAnimationManager$BaseAnimatorListener.onAnimationEnd(BaseItemAnimationManager.java:227)
            at android.support.v4.view.ViewPropertyAnimatorCompatJB$1.onAnimationEnd(ViewPropertyAnimatorCompatJB.java:47)
            at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1030)
            at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1056)
            at android.animation.ValueAnimator.cancel(ValueAnimator.java:969)
            at android.view.ViewPropertyAnimator.animatePropertyBy(ViewPropertyAnimator.java:882)
            at android.view.ViewPropertyAnimator.animateProperty(ViewPropertyAnimator.java:838)
            at android.view.ViewPropertyAnimator.translationY(ViewPropertyAnimator.java:584)
            at android.support.v4.view.ViewPropertyAnimatorCompatICS.translationY(ViewPropertyAnimatorCompatICS.java:38)
            at android.support.v4.view.ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl.translationY(ViewPropertyAnimatorCompat.java:358)
            at android.support.v4.view.ViewPropertyAnimatorCompat.translationY(ViewPropertyAnimatorCompat.java:695)
            at com.h6ah4i.android.widget.advrecyclerview.animator.SwipeDismissItemAnimator$SwipeDismissItemMoveAnimationManager.onAnimationCancel(SwipeDismissItemAnimator.java:352)
            at com.h6ah4i.android.widget.advrecyclerview.animator.SwipeDismissItemAnimator$SwipeDismissItemMoveAnimationManager.onAnimationCancel(SwipeDismissItemAnimator.java:304)
            at com.h6ah4i.android.widget.advrecyclerview.animator.impl.BaseItemAnimationManager$BaseAnimatorListener.onAnimationCancel(BaseItemAnimationManager.java:236)
            at android.support.v4.view.ViewPropertyAnimatorCompatJB$1.onAnimationCancel(ViewPropertyAnimatorCompatJB.java:42)
            at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationCancel(ViewPropertyAnimator.java:1012)
            at android.animation.ValueAnimator.cancel(ValueAnimator.java:966)
            at android.view.ViewPropertyAnimator.cancel(ViewPropertyAnimator.java:412)
            at android.support.v4.view.ViewPropertyAnimatorCompatICS.cancel(ViewPropertyAnimatorCompatICS.java:102)
            at android.support.v4.view.ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl.cancel(ViewPropertyAnimatorCompat.java:438)
            at android.support.v4.view.ViewPropertyAnimatorCompat.cancel(ViewPropertyAnimatorCompat.java:1001)
            at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator.endAnimation(ItemSlidingAnimator.java:214)
            at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator.animateSlideInternal(ItemSlidingAnimator.java:165)
            at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator.animateSlideInternalCompat(ItemSlidingAnimator.java:125)
            at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator.slideToSpecifiedPositionInternal(ItemSlidingAnimator.java:77)
            at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator.slideToDefaultPosition(ItemSlidingAnimator.java:53)
            at com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwi
```

**Comment by LouisCo** [comment]
I finally found my issue: I was passing the root of my item layout as the container and it seems that your library don't like it and prefers to have a "useless" ViewGroup wrapping each item. If anyone have the same error, look at the examples xml list_items files.
Many thanks for this awesome library

**Comment by Shajeel-Afzal** [comment]
@LouisCAD can you please tell exactly how you solved this problem?

**Comment by LouisCAD** [comment]
@Shajeel-Afzal This comment should have your solution: https://github.com/h6ah4i/android-advancedrecyclerview/issues/315#issuecomment-257089806
