### ISSUE TITLE
onCheckCanExpandOrCollapseGroup can not cast child ViewHolder to group Viewholder

### ISSUE THREAD

**Issue by xgear-public** [h6ah4i/android-advancedrecyclerview#282]
Sometimes i receive crash reports that child ViewHolder casted to group Viewholder while onCheckCanExpandOrCollapseGroup is called (lib version is 0.8.7):

Fatal Exception: java.lang.ClassCastException: my.package.adapter.ChildViewHolder cannot be cast to my.package.adapter.GroupViewHolder
       at my.package.adapter.MyAdapter.onCheckCanExpandOrCollapseGroup(SourceFile:44)
       at com.h6ah4i.android.widget.advrecyclerview.expandable.ExpandableRecyclerViewWrapperAdapter.onTapItem(SourceFile:593)
       at com.h6ah4i.android.widget.advrecyclerview.expandable.RecyclerViewExpandableItemManager.handleActionUpOrCancel(SourceFile:286)
       at com.h6ah4i.android.widget.advrecyclerview.expandable.RecyclerViewExpandableItemManager.onInterceptTouchEvent(SourceFile:222)
       at com.h6ah4i.android.widget.advrecyclerview.expandable.RecyclerViewExpandableItemManager$1.onInterceptTouchEvent(SourceFile:95)
       at android.support.v7.widget.RecyclerView.dispatchOnItemTouchIntercept(SourceFile:2231)
       at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(SourceFile:2277)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1935)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2032)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2032)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2032)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2032)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2032)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2032)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2032)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2289)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2032)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2026)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1476)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2473)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(SourceFile:60)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(SourceFile:60)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1974)
       at android.view.View.dispatchPointerEvent(View.java:7396)
       at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3250)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3195)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4237)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4216)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4308)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:125)
       at android.os.Looper.loop(Looper.java:124)
       at android.app.ActivityThread.main(ActivityThread.java:4914)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:808)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:575)
       at dalvik.system.NativeStart.main(NativeStart.java)

Can you point me what can be a root cause of this issue?

**Comment by h6ah4i** [comment]
@xgear-public Hi. This kind of errors can be caused by a mismatch between the actual data set and the internal state of the [`ExpandablePositionTranslator`](https://github.com/h6ah4i/android-advancedrecyclerview/blob/0.9.2/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/expandable/ExpandablePositionTranslator.java). (The `ExpandablePositionTranslator` is a core class of the expandable feature of this library, it manages all groups/children position and convert to flat position.)

I am not sure whether this is a bug of this library or your implementation fault. Could you provide some info to investigate this issue?

- Which features are enabled?
 - [x] Expandable
 - [ ] Swipeable
 - [ ] Draggable
- Do you use any other libraries integrated with `RecyclerView`?
- Do you change the contents of data set?
- Do you use these methods?
  - [ ] `RecyclerView.Adapter.notifyDataSetChanged()`
  - [ ] `RecyclerView.Adapter.notifyItemChanged(int position, Object payload)`
  - [ ] `RecyclerView.Adapter.notifyItemChanged(int position)`
  - [ ] `RecyclerView.Adapter.notifyItemInserted(int position)`
  - [ ] `RecyclerView.Adapter.notifyItemMoved(int fromPosition, int toPosition)`
  - [ ] `RecyclerView.Adapter.notifyItemRangeChanged(int positionStart, int itemCount, Object payload)`
  - [ ] `RecyclerView.Adapter.notifyItemRangeChanged(int positionStart, int itemCount)`
  - [ ] `RecyclerView.Adapter.notifyItemRangeInserted(int positionStart, int itemCount)`
  - [ ] `RecyclerView.Adapter.notifyItemRangeRemoved(int positionStart, int itemCount)`
  - [ ] `RecyclerView.Adapter.notifyItemRemoved(int position)`
  - [ ] `RecyclerViewExpandableItemManager.notifyGroupItemChanged(int groupPosition)`
  - [ ] `RecyclerViewExpandableItemManager.notifyGroupAndChildrenItemsChanged(int groupPosition)`
  - [ ] `RecyclerViewExpandableItemManager.notifyGroupAndChildrenItemsChanged(int groupPosition, Object payload)`
  - [ ] `RecyclerViewExpandableItemManager.notifyChildrenOfGroupItemChanged(int groupPosition)`
  - [ ] `RecyclerViewExpandableItemManager.notifyChildrenOfGroupItemChanged(int groupPosition, Object payload)`
  - [ ] `RecyclerViewExpandableItemManager.notifyChildItemChanged(int groupPosition, int childPosition)`
  - [ ] `RecyclerViewExpandableItemManager.notifyChildItemChanged(int groupPosition, int childPosition, Object payload)`
  - [ ] `RecyclerViewExpandableItemManager.notifyChildItemRangeChanged(int groupPosition, int childPositionStart, int itemCount)`
  - [ ] `RecyclerViewExpandableItemManager.notifyChildItemRangeChanged(int groupPosition, int childPositionStart, int itemCount, Object payload)`
  - [ ] `RecyclerViewExpandableItemManager.notifyGroupItemInserted(int groupPosition)`
  - [ ] `RecyclerViewExpandableItemManager.notifyGroupItemInserted(int groupPosition, boolean expanded)`
  - [ ] `RecyclerViewExpandableItemManager.notifyGroupItemRangeInserted(int groupPositionStart, int itemCount)`
  - [ ] `RecyclerViewExpandableItemManager.notifyGroupItemRangeInserted(int groupPositionStart, int itemCount, boolean expanded)`
  - [ ] `RecyclerViewExpandableItemManager.notifyChildItemInserted(int groupPosition, int childPosition)`
  - [ ] `RecyclerViewExpandableItemManager.notifyChildItemRangeInserted(int groupPosition, int childPositionStart, int itemCount)`
  - [ ] `RecyclerViewExpandableItemManager.notifyGroupItemRemoved(int groupPosition)`
  - [ ] `RecyclerViewExpandableItemManager.notifyGroupItemRangeRemoved(int groupPositionStart, int itemCount)`
  - [ ] `RecyclerViewExpandableItemManager.notifyChildItemRemoved(int groupPosition, int childPosition)`
  - [ ] `RecyclerViewExpandableItemManager.notifyChildItemRangeRemoved(int groupPosition, int childPositionStart, int itemCount)`
  - [ ] `RecyclerViewExpandableItemManager.notifyGroupItemMoved(int fromGroupPosition, int toGroupPosition)`
  - [ ] `RecyclerViewExpandableItemManager.notifyChildItemMoved(int groupPosition, int fromChildPosition, int toChildPosition)`
  - [ ] `RecyclerViewExpandableItemManager.notifyChildItemMoved(int fromGroupPosition, int fromChildPosition, int toGroupPosition, int toChildPosition)`

Thanks.

**Comment by xgear-public** [comment]
Which features are enabled? - only expandable
Do you use any other libraries integrated with RecyclerView? - no
Do you change the contents of data set? - yes
Do you use these methods? - 
I extend from AbstractExpandableItemAdapter
use in consturctor setHasStableIds
RecyclerViewExpandableItemManager.notifyGroupItemChanged
notifyDataSetChanged
RecyclerViewExpandableItemManager.isGroupExpanded
RecyclerViewExpandableItemManager.notifyGroupItemChanged
RecyclerViewExpandableItemManager.isGroupExpanded
RecyclerViewExpandableItemManager.notifyGroupAndChildrenItemsChanged

inside of fragment
RecyclerViewExpandableItemManager.createWrappedAdapter
RefactoredDefaultItemAnimator
RecyclerViewExpandableItemManager.getExpandablePosition
RecyclerViewExpandableItemManager.getPackedPositionGroup
RecyclerViewExpandableItemManager.getPackedPositionChild

**Comment by h6ah4i** [comment]
Thanks, but I am not able to reproduce it yet 😢  

Does anyone have the same issue or able to reproduce it?

**Comment by xgear-public** [comment]
Can this problem appear if i change dataset but don't call notify* method? Actually i am 90% sure that root cause of problem - incorrect library use, or dataset consistency absence.

**Comment by h6ah4i** [comment]
> Can this problem appear if i change dataset but don't call notify* method?

Yes, that can cause the inconsistency problems, so always need to use `notify*` method propery. If you do not have confidence, using `notifyDataSetChanged()` is the most safe one (but it's most heavy method).

**Comment by xgear-public** [comment]
Thanks for support and for such a good library!
