### ISSUE TITLE
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.h6ah4i.android.widget.advrecyclerview.b.e.b(android.support.v7.widget.RecyclerView$ViewHolder)' on a null object reference

### ISSUE THREAD

**Issue by chengxuyuanqiangzi** [h6ah4i/android-advancedrecyclerview#314]
错误内容Unable to destroy activity {com.haizhi.oa/com.haizhi.oa.projects.TaskListNActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.h6ah4i.android.widget.advrecyclerview.b.e.b(android.support.v7.widget.RecyclerView$ViewHolder)' on a null object reference;
错误原因java.lang.NullPointerException: Attempt to invoke virtual method 'void com.h6ah4i.android.widget.advrecyclerview.b.e.b(android.support.v7.widget.RecyclerView$ViewHolder)' on a null object reference;
App构建时间2016-10-10 16:58:36;
java.lang.RuntimeException: Unable to destroy activity {com.haizhi.oa/com.haizhi.oa.projects.TaskListNActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.h6ah4i.android.widget.advrecyclerview.b.e.b(android.support.v7.widget.RecyclerView$ViewHolder)' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3838)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3856)
	at android.app.ActivityThread.access$1500(ActivityThread.java:153)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5438)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.h6ah4i.android.widget.advrecyclerview.b.e.b(android.support.v7.widget.RecyclerView$ViewHolder)' on a null object reference
	at com.h6ah4i.android.widget.advrecyclerview.b.l.onViewRecycled(TbsSdkJava:77)
	at android.support.v7.widget.RecyclerView$Recycler.dispatchViewRecycled(TbsSdkJava:5171)
	at android.support.v7.widget.RecyclerView$Recycler.addViewHolderToRecycledViewPool(TbsSdkJava:4936)
	at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(TbsSdkJava:4919)
	at android.support.v7.widget.RecyclerView.removeAnimatingView(TbsSdkJava:1127)
	at android.support.v7.widget.RecyclerView.access$6400(TbsSdkJava:147)
	at android.support.v7.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(TbsSdkJava:10294)
	at android.support.v7.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(TbsSdkJava:10794)
	at android.support.v7.widget.SimpleItemAnimator.dispatchRemoveFinished(TbsSdkJava:265)
	at android.support.v7.widget.DefaultItemAnimator$4.onAnimationEnd(TbsSdkJava:208)
	at android.support.v4.view.ViewPropertyAnimatorCompatJB$1.onAnimationEnd(TbsSdkJava:47)
	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1114)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
	at android.animation.ValueAnimator.cancel(ValueAnimator.java:1140)
	at android.view.ViewPropertyAnimator.cancel(ViewPropertyAnimator.java:427)
	at android.support.v4.view.ViewPropertyAnimatorCompatICS.cancel(TbsSdkJava:102)
	at android.support.v4.view.ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl.cancel(TbsSdkJava:464)
	at android.support.v4.view.ViewPropertyAnimatorCompat.cancel(TbsSdkJava:1063)
	at android.support.v7.widget.DefaultItemAnimator.cancelAll(TbsSdkJava:632)
	at android.support.v7.widget.DefaultItemAnimator.endAnimations(TbsSdkJava:622)
	at android.support.v7.widget.RecyclerView.onDetachedFromWindow(TbsSdkJava:2137)
	at android.view.View.dispatchDetachedFromWindow(View.java:14579)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3072)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3064)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3064)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4604)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4577)
	at android.view.ViewGroup.removeView(ViewGroup.java:4508)
	at android.support.v4.app.FragmentManagerImpl.moveToState(TbsSdkJava:1165)
	at android.support.v4.app.FragmentManagerImpl.moveToState(TbsSdkJava:1252)
	at android.support.v4.app.FragmentManagerImpl.moveToState(TbsSdkJava:1234)
	at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(TbsSdkJava:2083)
	at android.support.v4.app.FragmentController.dispatchDestroy(TbsSdkJava:244)
	at android.support.v4.app.FragmentActivity.onDestroy(TbsSdkJava:368)
	at android.support.v7.app.AppCompatActivity.onDestroy(TbsSdkJava:203)
	at com.haizhi.oa.core.activity.BaseActivity.onDestroy(TbsSdkJava:163)
	at android.app.Activity.performDestroy(Activity.java:6474)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1143)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3825)
	... 9 more
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.h6ah4i.android.widget.advrecyclerview.b.e.b(android.support.v7.widget.RecyclerView$ViewHolder)' on a null object reference
	at com.h6ah4i.android.widget.advrecyclerview.b.l.onViewRecycled(TbsSdkJava:77)
	at android.support.v7.widget.RecyclerView$Recycler.dispatchViewRecycled(TbsSdkJava:5171)
	at android.support.v7.widget.RecyclerView$Recycler.addViewHolderToRecycledViewPool(TbsSdkJava:4936)
	at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(TbsSdkJava:4919)
	at android.support.v7.widget.RecyclerView.removeAnimatingView(TbsSdkJava:1127)
	at android.support.v7.widget.RecyclerView.access$6400(TbsSdkJava:147)
	at android.support.v7.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(TbsSdkJava:10294)
	at android.support.v7.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(TbsSdkJava:10794)
	at android.support.v7.widget.SimpleItemAnimator.dispatchRemoveFinished(TbsSdkJava:265)
	at android.support.v7.widget.DefaultItemAnimator$4.onAnimationEnd(TbsSdkJava:208)
	at android.support.v4.view.ViewPropertyAnimatorCompatJB$1.onAnimationEnd(TbsSdkJava:47)
	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1114)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
	at android.animation.ValueAnimator.cancel(ValueAnimator.java:1140)
	at android.view.ViewPropertyAnimator.cancel(ViewPropertyAnimator.java:427)
	at android.support.v4.view.ViewPropertyAnimatorCompatICS.cancel(TbsSdkJava:102)
	at android.support.v4.view.ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl.cancel(TbsSdkJava:464)
	at android.support.v4.view.ViewPropertyAnimatorCompat.cancel(TbsSdkJava:1063)
	at android.support.v7.widget.DefaultItemAnimator.cancelAll(TbsSdkJava:632)
	at android.support.v7.widget.DefaultItemAnimator.endAnimations(TbsSdkJava:622)
	at android.support.v7.widget.RecyclerView.onDetachedFromWindow(TbsSdkJava:2137)
	at android.view.View.dispatchDetachedFromWindow(View.java:14579)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3072)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3064)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3064)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4604)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4577)
	at android.view.ViewGroup.removeView(ViewGroup.java:4508)
	at android.support.v4.app.FragmentManagerImpl.moveToState(TbsSdkJava:1165)
	at android.support.v4.app.FragmentManagerImpl.moveToState(TbsSdkJava:1252)
	at android.support.v4.app.FragmentManagerImpl.moveToState(TbsSdkJava:1234)
	at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(TbsSdkJava:2083)
	at android.support.v4.app.FragmentController.dispatchDestroy(TbsSdkJava:244)
	at android.support.v4.app.FragmentActivity.onDestroy(TbsSdkJava:368)
	at android.support.v7.app.AppCompatActivity.onDestroy(TbsSdkJava:203)
	at com.haizhi.oa.core.activity.BaseActivity.onDestroy(TbsSdkJava:163)
	at android.app.Activity.performDestroy(Activity.java:6474)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1143)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3825)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3856)
	at android.app.ActivityThread.access$1500(ActivityThread.java:153)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5438)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by chengxuyuanqiangzi** [comment]
use version:0.8.4

**Comment by h6ah4i** [comment]
@chengxuyuanqiangzi Hi. Could you also upload the obfuscated stack trace? Thanks.

**Comment by chengxuyuanqiangzi** [comment]
@h6ah4i I'm sorry, can't capture stack information, this is the online crash
