### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: Tmp detached view should be removed from RecyclerView before it can be recycled

### ISSUE THREAD

**Issue by MariusBoepple** [h6ah4i/android-advancedrecyclerview#315]
Got the following crash several times:
Version: 0.9.2
Android Versions: 6.0 and 6.0.1
`````
Fatal Exception: java.lang.IllegalArgumentException: Tmp detached view should be removed from RecyclerView before it can be recycled: ViewHolder{6645ba3 position=6 id=21474836480, oldPos=-1, pLpos:-1 tmpDetached no parent}
       at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5238)
       at android.support.v7.widget.RecyclerView.removeAnimatingView(RecyclerView.java:1198)
       at android.support.v7.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(RecyclerView.java:10834)
       at android.support.v7.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:11334)
       at android.support.v7.widget.SimpleItemAnimator.dispatchAddFinished(SimpleItemAnimator.java:289)
       at android.support.v7.widget.DefaultItemAnimator$5.onAnimationEnd(DefaultItemAnimator.java:242)
       at android.support.v4.view.ViewPropertyAnimatorCompatJB$1.onAnimationEnd(ViewPropertyAnimatorCompatJB.java:47)
       at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1114)
       at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
       at android.animation.ValueAnimator.cancel(ValueAnimator.java:1140)
       at android.view.ViewPropertyAnimator.cancel(ViewPropertyAnimator.java:427)
       at android.support.v4.view.ViewPropertyAnimatorCompatICS.cancel(ViewPropertyAnimatorCompatICS.java:102)
       at android.support.v4.view.ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl.cancel(ViewPropertyAnimatorCompat.java:464)
       at android.support.v4.view.ViewPropertyAnimatorCompat.cancel(ViewPropertyAnimatorCompat.java:1063)
       at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator.endAnimation(ItemSlidingAnimator.java:390)
       at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator.animateSlideInternal(ItemSlidingAnimator.java:351)
       at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator.animateSlideInternalCompat(ItemSlidingAnimator.java:251)
       at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator.slideToSpecifiedPositionInternal(ItemSlidingAnimator.java:154)
       at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator.slideToDefaultPosition(ItemSlidingAnimator.java:68)
       at com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager.slideItem(RecyclerViewSwipeManager.java:760)
       at com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager.applySlideItem(RecyclerViewSwipeManager.java:848)
       at com.h6ah4i.android.widget.advrecyclerview.swipeable.SwipeableItemWrapperAdapter.onBindViewHolder(SwipeableItemWrapperAdapter.java:142)
       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5858)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5094)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4970)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3124)
       at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1522)
       at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4389)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
       at android.view.Choreographer.doCallbacks(Choreographer.java:695)
       at android.view.Choreographer.doFrame(Choreographer.java:628)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
````

**Comment by h6ah4i** [comment]
Hi. Thanks for the issue report.

I guess you are returning `itemView` for the `getSwipeableContainerView()` method. Please wrap with an another view and use that for `getSwipeableContainerView()`.


```xml
<!-- for itemView -->
<FrameLayout android:id="@+id/view_for_item_view">
    <!-- for getSwipeableContainerView() -->
    <FrameLayout android:id="@+id/view_for_swipe_container">
        <!-- contents -->
        <TextView />
         ...
    </FrameLayout>
</FrameLayout>
```

```java
class MyViewHolder extends AbstractSwipeableItemViewHolder {
    View swipeContainer;

    MyViewHolder(View v) {
        super(v);
        swipeContainer = v.findViewById(R.id.view_for_swipe_container);
    }

    @Override
    public View getSwipeableContainerView() {
        return swipeContainer;   // do not use itemView here!
    }
}
```

---

Related issue: #26

**Comment by MariusBoepple** [comment]
I think my code should work.. if it would be wrong, there should be more crashes. Currently I got 4 crashes in one month with a few hundred sessions a day.
```xml
<!-- root view -->
<RelativeLayout>
    <!-- underlying views -->
    ...
    <RelativeLayout  android:id="@+id/container">
        <!-- content views -->
         ...
    </RelativeLayout>
</RelativeLayout>
```

```java
static abstract class BaseViewHolder extends AbstractDraggableSwipeableItemViewHolder {
        ViewGroup mContainer;

        BaseViewHolder(View v) {
            super(v);
            mContainer = (ViewGroup) v.findViewById(R.id.container);
        }

        @Override
        public View getSwipeableContainerView() {
            return mContainer;
        }
    }
```

**Comment by h6ah4i** [comment]
Hmm... I checked the stack trace dump again and I have convinced that the culprit is the `getSwipeableContainerView()` which returns `itemView`.

Does your list contains multiple types of item views? If not swipeable items (e.g. section headers, spacers) also extends the same `BaseViewHolder`, `getSwipeableContainerView()` might return `itemView`.

```xml
<!-- root view -->
<RelativeLayout android:id="@+id/container">
    <!-- content views -->
    <TextView />
    ...
</RelativeLayout>
```
