### ISSUE TITLE
java.lang.IllegalArgumentException: Group ID value is out of range. (groupId = -991542614)

### ISSUE THREAD

**Issue by guidedways** [h6ah4i/android-advancedrecyclerview#321]
So I haven't changed anything in my code. I've just updated the library to v.10 and the app crashes while launching. Any idea what need to be fixed / changed? How could the Group IDs have been out of range when it was fine the whole year before?

```
11-17 13:19:04.322 23988-23988/ java.lang.IllegalStateException: Layout state should be one of 100 but it is 10
11-17 13:19:04.323 23988-23988/     at android.support.v7.widget.RecyclerView$State.assertLayoutStep(RecyclerView.java:10881)
11-17 13:19:04.323 23988-23988/     at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3396)
11-17 13:19:04.323 23988-23988/     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3199)
11-17 13:19:04.323 23988-23988/     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3632)
11-17 13:19:04.323 23988-23988/     at android.view.View.layout(View.java:16636)
11-17 13:19:04.323 23988-23988/     at android.view.ViewGroup.layout(ViewGroup.java:5437)
11-17 13:19:04.323 23988-23988/     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
11-17 13:19:04.323 23988-23988/     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
11-17 13:19:04.323 23988-23988/     at android.view.View.layout(View.java:16636)
11-17 13:19:04.323 23988-23988/     at android.view.ViewGroup.layout(ViewGroup.java:5437)
11-17 13:19:04.323 23988-23988/     at com.myapp.app.v2.components.slidingpanels.ThreePanelPhoneSliderFrameLayout.performCustomLayout(ThreePanelPhoneSliderFrameLayout.java:603)
11-17 13:19:04.323 23988-23988/     at com.myapp.app.v2.components.slidingpanels.ThreePanelPhoneSliderFrameLayout.onLayout(ThreePanelPhoneSliderFrameLayout.java:410)
11-17 13:19:04.323 23988-23988/     at android.view.View.layout(View.java:16636)
11-17 13:19:04.323 23988-23988/     at android.view.ViewGroup.layout(ViewGroup.java:5437)
11-17 13:19:04.323 23988-23988/     at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
11-17 13:19:04.323 23988-23988/     at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
11-17 13:19:04.323 23988-23988/     at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1367)
11-17 13:19:04.323 23988-23988/     at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:849)
11-17 13:19:04.323 23988-23988/     at android.view.View.layout(View.java:16636)
11-17 13:19:04.323 23988-23988/     at android.view.ViewGroup.layout(ViewGroup.java:5437)
11-17 13:19:04.323 23988-23988/     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
11-17 13:19:04.323 23988-23988/     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
11-17 13:19:04.323 23988-23988/     at android.view.View.layout(View.java:16636)
11-17 13:19:04.323 23988-23988/     at android.view.ViewGroup.layout(ViewGroup.java:5437)
11-17 13:19:04.323 23988-23988/     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
11-17 13:19:04.324 23988-23988/     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
11-17 13:19:04.324 23988-23988/     at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
11-17 13:19:04.324 23988-23988/     at android.view.View.layout(View.java:16636)
11-17 13:19:04.324 23988-23988/     at android.view.ViewGroup.layout(ViewGroup.java:5437)
11-17 13:19:04.324 23988-23988/     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
11-17 13:19:04.324 23988-23988/     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
11-17 13:19:04.324 23988-23988/     at android.view.View.layout(View.java:16636)
11-17 13:19:04.324 23988-23988/     at android.view.ViewGroup.layout(ViewGroup.java:5437)
11-17 13:19:04.324 23988-23988/     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
11-17 13:19:04.324 23988-23988/     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
11-17 13:19:04.324 23988-23988/     at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
11-17 13:19:04.324 23988-23988/     at android.view.View.layout(View.java:16636)
11-17 13:19:04.324 23988-23988/     at android.view.ViewGroup.layout(ViewGroup.java:5437)
11-17 13:19:04.324 23988-23988/     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
11-17 13:19:04.324 23988-23988/     at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
11-17 13:19:04.324 23988-23988/     at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
11-17 13:19:04.324 23988-23988/     at android.view.View.layout(View.java:16636)
11-17 13:19:04.324 23988-23988/     at android.view.ViewGroup.layout(ViewGroup.java:5437)
11-17 13:19:04.324 23988-23988/     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
11-17 13:19:04.324 23988-23988/     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
11-17 13:19:04.324 23988-23988/     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
11-17 13:19:04.324 23988-23988/     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
11-17 13:19:04.324 23988-23988/     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
11-17 13:19:04.324 23988-23988/     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
11-17 13:19:04.324 23988-23988/     at android.view.Choreographer.doFrame(Choreographer.java:606)
11-17 13:19:04.324 23988-23988/     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
11-17 13:19:04.324 23988-23988/     at android.os.Handler.handleCallback(Handler.java:739)
11-17 13:19:04.324 23988-23988/     at android.os.Handler.dispatchMessage(Handler.java:95)
11-17 13:19:04.324 23988-23988/     at android.os.Looper.loop(Looper.java:148)
11-17 13:19:04.325 23988-23988/     at android.app.ActivityThread.main(ActivityThread.java:5417)
11-17 13:19:04.325 23988-23988/     at java.lang.reflect.Method.invoke(Native Method)
11-17 13:19:04.325 23988-23988/     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-17 13:19:04.325 23988-23988/     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by h6ah4i** [comment]
@guidedways Hi. Thanks for the issue report. But unfortunately, this is an intentional change since v0.10.0. The change of the item ID handling is necessary to support ComposedAdapter (headers, footers ...).

| Library version | Group ID | Child ID | Note |
|---|---|---|---|---|
| **v0.9.x** | 31 bit integer | 32 bit integer | ID value range is not checked, unsupported range bits are just ignored (masked) |
| **v0.10.0** (*1) | 28 bit integer | 28 bit integer | ID value range is strictly checked |

(*1) [How ARV uses item ID - ItemIdComposer](http://h6ah4i.com/android-advancedrecyclerview/wrapper-adapter/composed-adapter/#itemidcomposer)

---

I do not recommend to use `hashId()` for item ID value for RecyclerView. The method does not meet the requirement what `RecyclerView` expects;

- it may be returns `-1`(= `RecyclerView.NO_ID`)
- it may be returns the same value for different objects
- adapter must return unique value for each items (even if the adapter holds multiple items which returns the same hash code)

Also, Advanced RecyclerView has the following additional limitations for item IDs;

- Non-expandable adapter
  - Item ID: 56 bit (`-2^55` .. `2^55 - 1`)
- Expandable adapter
  - Group item ID: 28 bit (`-2^27` .. `2^27 - 1`)
  - Child item ID: 28 bit (`-2^27` .. `2^27 - 1`)
