### ISSUE TITLE
IllegalStateException: Inconsistency detected! getSwipeableContainerView() returns itemView when updating from 0.10.0 to 0.10.1

### ISSUE THREAD

**Issue by MariusBoepple** [h6ah4i/android-advancedrecyclerview#336]
When updating from `0.10.0` to `0.10.1` I can't click on any of the items in my list anymore. Always crashes with the following stacktrace:
````
01-11 15:54:25.368 10318-10318/com.example.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.example.app, PID: 10318
                                                                           java.lang.IllegalStateException: Inconsistency detected! getSwipeableContainerView() returns itemView
                                                                               at com.h6ah4i.android.widget.advrecyclerview.swipeable.SwipeableViewHolderUtils.getSwipeableContainerView(SwipeableViewHolderUtils.java:36)
                                                                               at com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager.applySlideItem(RecyclerViewSwipeManager.java:886)
                                                                               at com.h6ah4i.android.widget.advrecyclerview.swipeable.SwipeableItemWrapperAdapter.onBindViewHolder(SwipeableItemWrapperAdapter.java:146)
                                                                               at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6312)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5258)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5521)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5363)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5359)
                                                                               at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2141)
                                                                               at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1525)
                                                                               at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1488)
                                                                               at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:585)
                                                                               at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3506)
                                                                               at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3254)
                                                                               at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3767)
                                                                               at android.view.View.layout(View.java:17637)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                               at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
                                                                               at android.view.View.layout(View.java:17637)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                               at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                               at android.view.View.layout(View.java:17637)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                               at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                               at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                               at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1375)
                                                                               at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
                                                                               at android.view.View.layout(View.java:17637)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                               at android.view.View.layout(View.java:17637)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                               at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                                               at android.view.View.layout(View.java:17637)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                               at android.view.View.layout(View.java:17637)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                               at android.view.View.layout(View.java:17637)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                               at android.view.View.layout(View.java:17637)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
01-11 15:54:25.368 10318-10318/com.example.app E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                               at android.view.View.layout(View.java:17637)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                               at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
                                                                               at android.view.View.layout(View.java:17637)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                               at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                               at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
````

**Comment by h6ah4i** [comment]
Hi. That is an expected behavior.

I have added the assertion code to avoid reproducing the issue #26 and #315. Please check my responses on the issue #315 for more details. Thanks.
