### ISSUE TITLE
why is this Exception?

### ISSUE THREAD

**Issue by laxminarayan192** [h6ah4i/android-advancedrecyclerview#338]
FATAL EXCEPTION: main
                                                                        Process: com.grabandgo.consumer, PID: 16533
                                                                        java.lang.ClassCastException: com.grabbngo.adapters.ExpandableAdapter$ChildHolder cannot be cast to com.grabbngo.adapters.ExpandableAdapter$GroupHolder
                                                                            at com.grabbngo.adapters.ExpandableAdapter.onCheckCanExpandOrCollapseGroup(ExpandableAdapter.java:26)
                                                                            at com.h6ah4i.android.widget.advrecyclerview.expandable.ExpandableRecyclerViewWrapperAdapter.onTapItem(ExpandableRecyclerViewWrapperAdapter.java:684)
                                                                            at com.h6ah4i.android.widget.advrecyclerview.expandable.RecyclerViewExpandableItemManager.handleActionUpOrCancel(RecyclerViewExpandableItemManager.java:282)
                                                                            at com.h6ah4i.android.widget.advrecyclerview.expandable.RecyclerViewExpandableItemManager.onInterceptTouchEvent(RecyclerViewExpandableItemManager.java:218)
                                                                            at com.h6ah4i.android.widget.advrecyclerview.expandable.RecyclerViewExpandableItemManager$1.onInterceptTouchEvent(RecyclerViewExpandableItemManager.java:95)
                                                                            at android.support.v7.widget.RecyclerView.dispatchOnItemTouchIntercept(RecyclerView.java:2572)
                                                                            at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:2618)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1996)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
                                                                            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2594)
                                                                            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1837)
                                                                            at android.app.Activity.dispatchTouchEvent(Activity.java:2797)
                                                                            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2555)
                                                                            at android.view.View.dispatchPointerEvent(View.java:8799)
                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4647)
                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4505)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4019)
                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4072)
                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4038)
                                                                            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4175)
                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4046)
                                                                            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4232)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4019)
                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4072)
                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4038)
                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4046)
                                                                        	at android.view.ViewRootImpl$InputStage.deliver(ViewR

**Comment by h6ah4i** [comment]
Hi. Maybe this issue is the same as #282. I think this kind of issues will be caused when underlying data set is changed without calling a corresponding `notify*` method of the adapter.

- [onCheckCanExpandOrCollapseGroup can not cast child ViewHolder to group Viewholder #282](https://github.com/h6ah4i/android-advancedrecyclerview/issues/282)
