### ISSUE TITLE
illegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling

### ISSUE THREAD

**Issue by guidedways** [h6ah4i/android-advancedrecyclerview#339]
Seeing a lot of these in crashlytics. 

`Fatal Exception: java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling
       at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(SourceFile:2457)
       at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(SourceFile:4811)
       at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(SourceFile:10793)
       at android.support.v7.widget.RecyclerView$Adapter.notifyItemRangeInserted(SourceFile:6490)
       at com.h6ah4i.android.widget.advrecyclerview.expandable.ExpandableRecyclerViewWrapperAdapter.expandGroup(SourceFile:764)
       at com.h6ah4i.android.widget.advrecyclerview.expandable.ExpandableRecyclerViewWrapperAdapter.onTapItem(SourceFile:693)
       at com.h6ah4i.android.widget.advrecyclerview.expandable.RecyclerViewExpandableItemManager.handleActionUpOrCancel(SourceFile:291)
       at com.h6ah4i.android.widget.advrecyclerview.expandable.RecyclerViewExpandableItemManager.onInterceptTouchEvent(SourceFile:224)
       at com.h6ah4i.android.widget.advrecyclerview.expandable.RecyclerViewExpandableItemManager$1.onInterceptTouchEvent(SourceFile:101)
       at android.support.v7.widget.RecyclerView.dispatchOnItemTouchIntercept(SourceFile:2509)
       at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(SourceFile:2555)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2368)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2810)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1863)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3047)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(SourceFile:67)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2771)
       at android.view.View.dispatchPointerEvent(View.java:10229)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5352)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5188)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4628)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4681)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4647)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4789)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4655)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4846)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4628)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4681)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4647)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4655)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4628)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7325)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7203)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7164)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7435)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:143)
       at android.app.ActivityThread.main(ActivityThread.java:7230)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by guidedways** [comment]
Elsewhere on stackoverflow I read that for such errors one must fallback to using a Handler.post(new Runnable...) to avoid such crashes.

**Comment by h6ah4i** [comment]
Thanks for the issue report. I will take a look at it.

**Comment by h6ah4i** [comment]
@guidedways Hi. I have just released v0.10.3 and it fixed this issue. Thank you always for your help.
