### ISSUE TITLE
Fatal crash found in Fabric

### ISSUE THREAD

**Issue by guidedways** [h6ah4i/android-advancedrecyclerview#345]
Ever since AdvancedRecyclerView put the new limits on the Group / Child IDs, I've been seeing dozens of the following errors popup in Fabric. Sadly, I've tripple checked and I'm certain I'm using unique, stable IDs everywhere. The stack trace also doesn't help as it doesn't tell me which recycler is complaining (there are many within the app). The `id` however looks suspicious since that looks like one of those transformed IDs that advanced recycler uses to identify groups and children uniquely. Any idea what I should do?

```
Fatal Exception: java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
 ViewHolder 1:ViewHolder{183764a position=7 id=536870919, oldPos=-1, pLpos:-1 not recyclable(1)} 
 View Holder 2:ViewHolder{4866e76 position=1 id=536870919, oldPos=-1, pLpos:-1}
       at android.support.v7.widget.RecyclerView.handleMissingPreInfoForChangeError(SourceFile:3636)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(SourceFile:3564)
       at android.support.v7.widget.RecyclerView.dispatchLayout(SourceFile:3265)
       at android.support.v7.widget.RecyclerView.onLayout(SourceFile:3767)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5814)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5814)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5814)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5814)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5814)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5814)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5814)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5814)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
       at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3193)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5814)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2666)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2367)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
       at android.view.Choreographer.doCallbacks(Choreographer.java:695)
       at android.view.Choreographer.doFrame(Choreographer.java:631)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by guidedways** [comment]
Just want to add a bit more context. I've gone through crash logs for the last 3 days, and around 10 new came in with similar stacktraces. The actual view positions of the viewholders don't match, but their offending IDs are always `536870919`. 

In recent days I've reviewed my code twice, moved to using RxJava2 to ensure proper queuing and handling of refreshes, but the crashes haven't gone away. 

I'm sorry I'm unable to provide you with more details as the crashes don't seem to reference any of the app's actual code. However looking at the logs, it does seem to be a happening around the time the Activity either `onPauses`s or `onResume`s - which means somehow the data it's holding is either not valid or the recyclerview is detailing with incorrect IDs somehow.

What's even more strange is that if I supply each of my Viewholders a static ID (such as the value `2`) - the app does *not* crash, even though I've set `setHasStableIds(true)`. So AdvancedRecyclerView is certainly transforming these IDs in a way that they somehow remain unique nonetheless, but that doesn't explain why the app is randomly crashing at other times.

**Comment by h6ah4i** [comment]
I carefully checked the stack trace message and I noticed that there is an important hint in the it.

```
 ViewHolder 1:ViewHolder{..., oldPos=-1, pLpos:-1 not recyclable(1)} 
 View Holder 2:ViewHolder{..., oldPos=-1, pLpos:-1}
```

The ViewHolder1 is marked as **not recyclable**. It means the ViewHolder1 is now animating, but somehow RecyclerView is trying to reuse it! I guess this issue occurs on dataset change happens while animating item(s).


This is my hypothesis to reproducing the issue:

- Setting animations duration longer 
- Making data set change frequently

(I will try to make an experiment to proof my idea later.)

---

> What's even more strange is that if I supply each of my Viewholders a static ID (such as the value 2) - the app does not crash, even though I've set setHasStableIds(true).  

On my experiment result, RecyclerView does not crash until calling any `notify` methods. Also I discovered that the `IllegalStateException` only occurs if change animations are enabled. (`setSupportsChangeAnimations(true)`). When change animations are disabled, `NullPointerException` will be raised.

> So AdvancedRecyclerView is certainly transforming these IDs in a way that they somehow remain unique nonetheless, but that doesn't explain why the app is randomly crashing at other times.

Yes, AdvancedRecyclerView transforms item IDs, BUT the transformed IDs will not be unique if source IDs are not unique. The transformation is done by [ItemIdComposer](https://github.com/h6ah4i/android-advancedrecyclerview/blob/master/library/src/main/java/com/h6ah4i/android/widget/advrecyclerview/adapter/ItemIdComposer.java) class, they are simple bit operations. The reported ID `536870919` can be decomposed like this: 

```python
# using python:

# Combined ID - HEX:
>>> "0x%016x" % 536870919
'0x0000000020000007'

# Group ID: middle 28 bits
>>> "0x%07x" % ((536870919 >> 28) & ((1 << 28) - 1))
'0x0000002'

# Child ID: lower 28 bits
>>> "0x%07x" % ((536870919 >> 0) & ((1 << 28) - 1))
'0x0000007'
```

**Comment by guidedways** [comment]
Thanks - yes, it's completely plausible that the user is changing the dataset often while it's still busy animating. Animations on the recycler view are indeed enabled. When a user makes a change, there is around 0.5seconds pause before triggering a refresh / however, some external UI event could trigger a change as well. Although I am sure the list 'waits' till it's finished refreshing, but as you know there's no guarantee to knowing exactly when notifyDatasetChanged() has finished laying out / animating.

Thanks for the breakdown of the IDs. Strange why it's always group '2' and child ID '7'! In the meanwhile I'll try and play with the animation duration to see if I can reproduce this reliably (as I haven't been able to so far).

**Comment by guidedways** [comment]
Any idea on this? I'm still seeing this as the most reason why the app is crashing. Thanks.

**Comment by tbsandee** [comment]
@guidedways Just a personal anecdote for you to consider: Many times  (>4) in the last few years I've thought "for sure" that my ID's are stable, etc. and ran into this very intermittent issue (the IllegalStateException). And every single time I eventually tracked down the issue as a problem in my id generation where I had overlapping id's. I use this library w/change animations as well triggered quite a bit. 

I'd also check which version of the support library too, as every new version of that seems to fix some RecyclerView bugs.

**Comment by guidedways** [comment]
@tbsandee thanks, you know what, that might just be true. Although I've gone over the code numerous times, I'm willing to accept that there's some weird case where the activity possibly pauses / resumes and the adapter returns junk (as I've been able to track this down a bit). I can for now happily close this issue.
