### ISSUE TITLE
NoClassDefFoundError AnimatorCompatHelper

### ISSUE THREAD

**Issue by vds2014** [h6ah4i/android-advancedrecyclerview#413]
I got error even updating the to last version : 

    compileSdkVersion 26
    buildToolsVersion "26.0.1"

   compile 'com.android.support:appcompat-v7:26.0.1'
    compile 'com.android.support:design:26.0.1'
    compile 'com.android.support:recyclerview-v7:26.0.1'
    compile 'com.android.support:cardview-v7:26.0.1'

compile('com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.10.6@aar') {
        transitive = true
    }

                                                               java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
                                                                   at com.h6ah4i.android.widget.advrecyclerview.animator.impl.BaseItemAnimationManager.resetAnimation(BaseItemAnimationManager.java:161)
                                                                   at com.h6ah4i.android.widget.advrecyclerview.animator.RefactoredDefaultItemAnimator$DefaultItemMoveAnimationManager.addPendingAnimation(RefactoredDefaultItemAnimator.java:312)
                                                                   at com.h6ah4i.android.widget.advrecyclerview.animator.GeneralItemAnimator.animateChange(GeneralItemAnimator.java:98)
                                                                   at com.h6ah4i.android.widget.advrecyclerview.animator.DraggableItemAnimator.animateChange(DraggableItemAnimator.java:39)
                                                                   at android.support.v7.widget.SimpleItemAnimator.animateChange(SimpleItemAnimator.java:163)
                                                                   at android.support.v7.widget.RecyclerView$4.processPersistent(RecyclerView.java:539)
                                                                   at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:239)
                                                                   at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3763)
                                                                   at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3421)
                                                                   at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
                                                                   at android.view.View.layout(View.java:16646)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                   at android.view.View.layout(View.java:16646)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                   at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1767)
                                                                   at android.view.View.layout(View.java:16646)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                   at android.view.View.layout(View.java:16646)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                   at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                   at android.view.View.layout(View.java:16646)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                   at android.view.View.layout(View.java:16646)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                   at android.view.View.layout(View.java:16646)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                   at android.view.View.layout(View.java:16646)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                   at android.view.View.layout(View.java:16646)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                   at android.view.View.layout(View.java:16646)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                   at android.view.View.layout(View.java:16646)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                   at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
                                                               	at android.view.View.layout(View.jav

**Comment by Havrl** [comment]
I am getting the same error after sdk and tools update (26.0.1).

**Comment by hoeggi** [comment]
#396

**Comment by h6ah4i** [comment]
@vds2014, @Havrl I have released v0.11.0 today which includes the fix of this issue 😉
