### ISSUE TITLE
NotClassDefFoundError

### ISSUE THREAD

**Issue by fmeneuhe** [h6ah4i/android-advancedrecyclerview#419]
I leave you the stacktrace, I am using com.android.support:recyclerview-v7:26.1.0:

Fatal Exception: java.lang.NoClassDefFoundError: android.support.v4.animation.AnimatorCompatHelper
       at com.h6ah4i.android.widget.advrecyclerview.animator.impl.BaseItemAnimationManager.resetAnimation(SourceFile:161)
       at com.h6ah4i.android.widget.advrecyclerview.animator.RefactoredDefaultItemAnimator$DefaultItemMoveAnimationManager.addPendingAnimation(SourceFile:312)
       at com.h6ah4i.android.widget.advrecyclerview.animator.GeneralItemAnimator.animateChange(SourceFile:98)
       at android.support.v7.widget.SimpleItemAnimator.animateChange(SourceFile:163)
       at android.support.v7.widget.RecyclerView$4.processPersistent(SourceFile:539)
       at android.support.v7.widget.ViewInfoStore.process(SourceFile:239)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(SourceFile:3763)
       at android.support.v7.widget.RecyclerView.dispatchLayout(SourceFile:3421)
       at android.support.v7.widget.RecyclerView.onLayout(SourceFile:3962)
       at android.view.View.layout(View.java:14858)
       at android.view.ViewGroup.layout(ViewGroup.java:4646)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:14858)
......

**Comment by ibcurly** [comment]
I get the same error when updating support libraries to api 26
I think this library needs to be update the google support library version.

**Comment by mehroshmmm** [comment]
Any updates on this ?

**Comment by hfahmy** [comment]
Yes, need a fix for this quickly. Your lib has no substitute!

**Comment by h6ah4i** [comment]
@fmeneuhe, @ibcurly , @mehroshmmm, @hfahmy 

Sorry for the very late response 🙇  I have just released v0.11.0 today and it includes the fix of this issue.
