### ISSUE TITLE
Dragging to the top of the list causes an error "No static method onPull"

### ISSUE THREAD

**Issue by moe70** [h6ah4i/android-advancedrecyclerview#427]
I copied the Draggable Swipeable example to my app and it crashes when I drag an item to the top of the list

```
Process: swipetest.swipedragtest, PID: 17852
java.lang.NoSuchMethodError: No static method onPull(Landroid/widget/EdgeEffect;FF)V in class Landroid/support/v4/widget/EdgeEffectCompat; or its super classes (declaration of 'android.support.v4.widget.EdgeEffectCompat' appears in /data/app/swipetest.swipedragtest-1/split_lib_dependencies_apk.apk:classes11.dex)
    at com.h6ah4i.android.widget.advrecyclerview.draggable.BaseEdgeEffectDecorator.pullFirstEdge(BaseEdgeEffectDecorator.java:131)
    at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.updateEdgeEffect(RecyclerViewDragDropManager.java:1435)
    at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.handleScrollOnDraggingInternalWithRecyclerView(RecyclerViewDragDropManager.java:1415)
    at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.handleScrollOnDragging(RecyclerViewDragDropManager.java:1228)
    at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager$ScrollOnDraggingProcessRunnable.run(RecyclerViewDragDropManager.java:2157)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:926)
    at android.view.Choreographer.doCallbacks(Choreographer.java:735)
    at android.view.Choreographer.doFrame(Choreographer.java:664)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:912)
    at android.os.Handler.handleCallback(Handler.java:761)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:156)
    at android.app.ActivityThread.main(ActivityThread.java:6523)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

```

**Comment by tnqv** [comment]
Anyone else already fixed this issue ? I also met this issue in my case .But not dragging an item to top, It was crashed with this problem by dragging randomly in the list then drop -> Sometime causes , sometime not.

**Comment by ammarasim** [comment]
Facing same issue. Any fix?

**Comment by zack-barakat** [comment]
I'm facing similar issue,
Any idea how to fix?

`Fatal Exception: java.lang.NoSuchMethodError: No static method invokeOnViewAttachedToWindow(Landroid/support/v7/widget/RecyclerView$Adapter;Landroid/support/v7/widget/RecyclerView$ViewHolder;I)V in class Lcom/h6ah4i/android/widget/advrecyclerview/utils/WrappedAdapterUtils; or its super classes (declaration of 'com.h6ah4i.android.widget.advrecyclerview.utils.WrappedAdapterUtils'
       at com.h6ah4i.android.widget.advrecyclerview.adapter.SimpleWrapperAdapter.onViewAttachedToWindow(SimpleWrapperAdapter.java:130)
       at com.h6ah4i.android.widget.advrecyclerview.adapter.SimpleWrapperAdapter.onViewAttachedToWindow(SimpleWrapperAdapter.java:121)
       at android.support.v7.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:6987)
       at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:758)
`

**Comment by yamal-coding** [comment]
I have fixed this issue by adding this in my implementation of DraggableItemAdapter:

    @Override
    public void onItemDragStarted(int position) {
        notifyDataSetChanged();
    }

    @Override
    public void onItemDragFinished(int fromPosition, int toPosition, boolean result) {
        notifyDataSetChanged();
    }
