### ISSUE TITLE
Error: Program type already present: com.h6ah4i.android.widget.advrecyclerview.BuildConfig

### ISSUE THREAD

**Issue by seljabali** [h6ah4i/android-advancedrecyclerview#472]
Release `0.11.0`
```
Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: com.h6ah4i.android.widget.advrecyclerview.BuildConfig
	at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:116)
	at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:74)
```

I tried avoiding downloading dependencies of the library:
```
implementation ('com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.11.0@aar') { 
  transitive = false
}
```

In [reading around](https://stackoverflow.com/questions/25103288/multiple-dex-files-define-my-package-buildconfig-cant-find-the-cause/26531074#26531074) it seems that different modules need to have different package names, which seems to be the case: `"com.h6ah4i.android.example.advrecyclerview"` & `"com.h6ah4i.android.widget.advrecyclerview"`, making me unsure what the problem is. 

Any help, or tips would be much appreciated!

**Comment by seljabali** [comment]
Updating New Relic somehow fixed it.
