### ISSUE TITLE
 ClassCastException, MyPlatformChildViewHolder cannot be MyPlatformGroupViewHolder

### ISSUE THREAD

**Issue by aizhunimei** [h6ah4i/android-advancedrecyclerview#54]
i click my child view ,then carsh. I don't know what happen,  Does anyone know it , thank you!

06-14 10:51:43.827  27849-27849/com.ypwl_p2phelper E/InputEventReceiver﹕ Exception dispatching input event.
06-14 10:51:43.828  27849-27849/com.ypwl_p2phelper E/MessageQueue-JNI﹕ Exception in MessageQueue callback: handleReceiveCallback
06-14 10:51:43.843  27849-27849/com.ypwl_p2phelper E/MessageQueue-JNI﹕ java.lang.ClassCastException: com.ypwl_p2phelper.adapter.TestMyPlatformDataAdapter$MyPlatformChildViewHolder cannot be cast to com.ypwl_p2phelper.adapter.TestMyPlatformDataAdapter$MyPlatformGroupViewHolder
            at com.ypwl_p2phelper.adapter.TestMyPlatformDataAdapter.onGetGroupItemSwipeReactionType(TestMyPlatformDataAdapter.java:35)
            at com.h6ah4i.android.widget.advrecyclerview.expandable.ExpandableRecyclerViewWrapperAdapter.onGetSwipeReactionType(ExpandableRecyclerViewWrapperAdapter.java:509)
            at com.h6ah4i.android.widget.advrecyclerview.swipeable.SwipeableItemWrapperAdapter.getSwipeReactionType(SwipeableItemWrapperAdapter.java:185)
            at com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager.handleActionDown(RecyclerViewSwipeManager.java:460)
            at com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager.onInterceptTouchEvent(RecyclerViewSwipeManager.java:389)
            at com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager$1.onInterceptTouchEvent(RecyclerViewSwipeManager.java:257)
            at android.support.v7.widget.RecyclerView.dispatchOnItemTouchIntercept(RecyclerView.java:1773)
            at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:1814)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1960)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
            at android.view.View.dispatchPointerEvent(View.java:8666)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5807)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5781)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5752)
            at android.view.Vi
06-14 10:51:43.843  27849-27849/com.ypwl_p2phelper D/AndroidRuntime﹕ Shutting down VM
    --------- beginning of crash
06-14 10:51:43.899  27849-27849/com.ypwl_p2phelper E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.ypwl_p2phelper, PID: 27849
    java.lang.ClassCastException: com.ypwl_p2phelper.adapter.TestMyPlatformDataAdapter$MyPlatformChildViewHolder cannot be cast to com.ypwl_p2phelper.adapter.TestMyPlatformDataAdapter$MyPlatformGroupViewHolder
            at com.ypwl_p2phelper.adapter.TestMyPlatformDataAdapter.onGetGroupItemSwipeReactionType(TestMyPlatformDataAdapter.java:35)
            at com.h6ah4i.android.widget.advrecyclerview.expandable.ExpandableRecyclerViewWrapperAdapter.onGetSwipeReactionType(ExpandableRecyclerViewWrapperAdapter.java:509)
            at com.h6ah4i.android.widget.advrecyclerview.swipeable.SwipeableItemWrapperAdapter.getSwipeReactionType(SwipeableItemWrapperAdapter.java:185)
            at com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager.handleActionDown(RecyclerViewSwipeManager.java:460)
            at com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager.onInterceptTouchEvent(RecyclerViewSwipeManager.java:389)
            at com.h6ah4i.android.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager$1.onInterceptTouchEvent(RecyclerViewSwipeManager.java:257)
            at android.support.v7.widget.RecyclerView.dispatchOnItemTouchIntercept(RecyclerView.java:1773)
            at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:1814)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1960)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
            at android.view.View.dispatchPointerEvent(View.java:8666)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5807)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5781)
            at android.view.ViewRootImpl.e
    --------- beginning of system

**Comment by h6ah4i** [comment]
Maybe this issue will be fixed by PR #72.
