### ISSUE TITLE
AbstractMethodError in RecyclerViewTouchActionGuardManager

### ISSUE THREAD

**Issue by fahimk** [h6ah4i/android-advancedrecyclerview#92]
I have a switch in the rows of my recyclerview, looks like it is causing an issue:

```java
java.lang.AbstractMethodError: abstract method not implemented
       at com.h6ah4i.android.widget.advrecyclerview.touchguard.RecyclerViewTouchActionGuardManager$1.onRequestDisallowInterceptTouchEvent(RecyclerViewTouchActionGuardManager.java)
       at android.support.v7.widget.RecyclerView.requestDisallowInterceptTouchEvent(RecyclerView.java:2123)
       at android.view.ViewGroup.requestDisallowInterceptTouchEvent(ViewGroup.java:2298)
       at android.view.ViewGroup.requestDisallowInterceptTouchEvent(ViewGroup.java:2298)
       at android.view.ViewGroup.requestDisallowInterceptTouchEvent(ViewGroup.java:2298)
       at android.view.ViewGroup.requestDisallowInterceptTouchEvent(ViewGroup.java:2298)
       at android.view.ViewGroup.requestDisallowInterceptTouchEvent(ViewGroup.java:2298)
       at android.support.v7.widget.SwitchCompat.onTouchEvent(SwitchCompat.java:660)
       at android.view.View.dispatchTouchEvent(View.java:7707)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
```

**Comment by h6ah4i** [comment]
That seems strange, looks like a mismatch of this library and the RecyclerView library. Can I see the output of the following command?
 

`./gradlew :app:dependencies`

(*) Note that `app` is the name of the application module of your project.

**Comment by fahimk** [comment]
```
+--- com.android.support:appcompat-v7:22.2.1
|    \--- com.android.support:support-v4:22.2.1 (*)
+--- com.android.support:recyclerview-v7:22.2.1
|    +--- com.android.support:support-annotations:22.2.1
|    \--- com.android.support:support-v4:22.2.1 (*)
+--- com.github.ksoichiro:android-observablescrollview:1.5.2
|    \--- com.android.support:recyclerview-v7:21.0.0 -> 22.2.1 (*)
+--- com.github.frankiesardo:linearlistview:1.0.1
+--- com.nispok:snackbar:2.10.7
|    +--- com.android.support:recyclerview-v7:22.0.0 -> 22.2.1 (*)
|    \--- com.android.support:support-annotations:22.0.0 -> 22.2.1
+--- org.sufficientlysecure:html-textview:1.2
+--- pl.droidsonroids.gif:android-gif-drawable:1.1.+ -> 1.1.7
+--- com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.7.1
|    +--- com.android.support:appcompat-v7:22.1.1 -> 22.2.1 (*)
|    \--- com.android.support:recyclerview-v7:22.1.1 -> 22.2.1 (*)
+--- com.h6ah4i.android.materialshadowninepatch:materialshadowninepatch:0.6.3
|    \--- com.android.support:support-v4:22.1.1 -> 22.2.1 (*)
```

**Comment by h6ah4i** [comment]
Thanks. You are using two libraries which depends on the `com.android.support:recyclerview-v7` library.

1. `com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.7.1` expects `22.1.1`
2. `com.github.ksoichiro:android-observablescrollview:1.5.2` expects `21.0.0` 

However, you are specifying `recyclerview-v7:22.2.1` on your project. The `RecyclerView. OnItemTouchListener` had changed its interface since `22.2.0`, that is why the `AbstractMethodError` exception occurs.

Related issue) [Upgrade to com.android.support:recyclerview-v7:22.2.0 #66](https://github.com/h6ah4i/android-advancedrecyclerview/issues/66)

---

### Proposed fix 1
Use the latest Advanced RecyclerView library, but may cause a compatibility issue with `observablescrollview`.
- `com.h6ah4i.android.widget.advrecyclerview:advrecyclerview:0.7.4`

### Proposed fix 2
Use old RecyclerView library.
- `com.android.support:recyclerview-v7:22.1.1`
